Repository dhis2/dhis2-android-capture-app, pull requests merged in 2019-11, with the labels that each got.

#957 refactor: updated translations
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-km/strings.xml
  app/src/main/res/values-lo/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-vi/strings.xml
Labels: translations

#960 fix(category option combo): Crash on event initial
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
Labels: bug

#961 fix: enable orgUnit field when event is referral
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Labels: bug

#962 fix(Search): Fixes search teis list when device is offline
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: bug

#964 fix(style): Object Style blocked new relationships
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
Labels: bug

#969 fix: Physical back button not showing empty/error field dialog
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: bug

#970 fix: Missing Tracked Entity Type icon in dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
  app/src/main/java/org/dhis2/utils/ObjectStyleUtils.java
  app/src/main/res/layout/fragment_tei_data_card_front.xml
Labels: bug

#971 fix(FilterManager): fixes bug with the period filter from-To and other
  app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
Labels: bug

#963 test: adds test on DataSetInitial
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialContract.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialModule.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialView.kt
  app/src/main/res/layout/activity_dataset_initial.xml
  app/src/test/java/org/dhis2/usecases/datasets/dataSetInitial/DataSetInitialPresenterTest.kt
Labels: Ready for merge, Unit Test

#968 test(DataSetDetail): Adds unit test to presenter, migrates to kotlin
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailAdapter.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailComponent.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailComponent.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailContract.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailView.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailViewHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailViewHolder.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDiffCallback.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDiffCallback.kt
  app/src/main/res/layout/activity_dataset_detail.xml
  app/src/main/res/layout/item_dataset.xml
  app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenterTest.kt
Labels: Ready for merge, Unit Test

#959 test(DataSetTable): [ANDROAPP-2496] Adds missing test to DataSetTablePresenter
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableComponent.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableComponent.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableView.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/TableCheckboxAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/TableCheckboxViewHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/test/java/org/dhis2/usescases/datasets/DataValuePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetInitial/DataSetInitialPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/reservedValues/ReservedValuePresenterTest.kt
  app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
Labels: Ready for merge, Unit Test

#966 test(Notes): Unit test in NotesPresenter
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesComponent.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesComponent.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesModule.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesView.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesViewholder.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesViewholder.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesPresenterTest.kt
Labels: Changes requested, Unit Test

#974 fix(granular sync): Sync dialog layout showed errors after sms sync
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/main/res/values/strings.xml
Labels: bug

#973 fix(dashboard): Crash for autogenerated events with attribute option combo
  app/src/main/java/org/dhis2/data/server/ServerComponent.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialog.java
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialog.kt
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialogComponent.kt
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialogModule.kt
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialogPresenter.kt
  app/src/test/java/org/dhis2/utils/customviews/CategoryComboDIalogPresenterTest.kt
Labels: Ready for merge, bug

#975 fix(TrackedEntityAttributeValue): Removes uid from Search and Dashboard
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
Labels: Ready for merge, waiting for approval

#972 test(ProgramStageSelection): add test cases and migrate to kotlin
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionAdapter.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionAdapter.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionComponent.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionComponent.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionContract.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionModule.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionModule.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionView.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionViewHolder.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionViewHolder.kt
  app/src/main/res/layout/activity_program_stage_selection.xml
  app/src/main/res/layout/item_program_stage.xml
  app/src/test/java/org/dhis2/usescases/programstageselection/ProgramStageSelectionPresenterTest.kt
Labels: Ready for merge, Unit Test

#978 fix: Crash when selecting Report Jira Issue in home screen
  app/src/main/java/org/dhis2/usescases/jira/JiraViewModel.kt
Labels: Ready for merge, bug

#980 fix: Crash when clicking on polygon widget for program with null feature type
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: Ready for merge, bug

#976 Updates in documentation for APK 2.0.0
  docs/dhis2_android_capture_app_INDEX.md
  docs/features-supported.md
  docs/new-android-specific-features.md
  docs/programs-specific-features.md
  docs/resources/images/image100.png
  docs/resources/images/image101.png
  docs/resources/images/image102.png
  docs/resources/images/image103.png
  docs/resources/images/image87.png
  docs/resources/images/image88.png
  docs/resources/images/image89.png
  docs/resources/images/image90.png
  docs/resources/images/image91.png
  docs/resources/images/image92.png
  docs/resources/images/image93.png
  docs/resources/images/image94.png
  docs/resources/images/image95.png
  docs/resources/images/image96.png
  docs/resources/images/image97.png
  docs/resources/images/image98.png
  docs/resources/images/image99.png
  docs/value-types-supported.md
Labels: Documentation

#977 test: adds test on AboutPresenter and migrates to kotlin
  app/src/main/java/org/dhis2/usescases/about/AboutComponent.java
  app/src/main/java/org/dhis2/usescases/about/AboutComponent.kt
  app/src/main/java/org/dhis2/usescases/about/AboutContracts.java
  app/src/main/java/org/dhis2/usescases/about/AboutFragment.java
  app/src/main/java/org/dhis2/usescases/about/AboutFragment.kt
  app/src/main/java/org/dhis2/usescases/about/AboutModule.java
  app/src/main/java/org/dhis2/usescases/about/AboutModule.kt
  app/src/main/java/org/dhis2/usescases/about/AboutPresenter.kt
  app/src/main/java/org/dhis2/usescases/about/AboutPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/about/AboutView.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/test/java/org/dhis2/usescases/about/AboutPresenterTest.kt
Labels: Ready for merge, Unit Test

#998 fix: allow user to select different OrgUnit
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Labels: Ready for merge, bug

#1003 chore(translations): sync Spanish translations from transifex (develop)
  app/src/main/res/values-es/strings.xml
Labels: translations

#997 fix: Fix random order for DE/Attributes marked with displayInList
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
Labels: bug, waiting for approval

#1000 fix(DataEntryAdapter): Scrolls when adding many field to the forms
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: bug, waiting for approval

#1025 fix: do not overlap label by orgUnit name
  app/src/main/res/layout/fragment_tei_data_card_front.xml
Labels: bug, waiting for approval

#1023 fix: Create event for TEI crash when drawable resource does not exist
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionViewHolder.java
Labels: Ready for merge, bug

#1027 fix: Bug order for DE/Attributes marked with displayInList when there is no sections
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
Labels: bug, waiting for approval

#1033 refactor(testing credentials): Change default credentials
  app/src/main/res/raw/testing_credentials.json
Labels: enhancement, waiting for approval

#1031 fix: Home loading is never hide after clean install
  app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
  app/src/test/java/org/dhis2/usecases/main/program/ProgramPresenterTest.kt
Labels: bug, waiting for approval

#1035 fix(settings): Event and TEI count had the wrong order
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
  app/src/main/res/values/strings.xml
Labels: Ready for merge, bug

#1034 fix(Forms): Eliminates the need to click twice to get the cursor on the chosen field
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: Ready for merge, bug

#1038 fix(developActivity): Icons tested individually to catch more errors
  app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
Labels: Ready for merge, bug, enhancement

#1040 fix: Centering % completation in circle custom view
  app/src/main/java/org/dhis2/utils/customviews/CircularCompletionView.java
Labels: Ready for merge, bug

#1030 fix(filters): Wrong options in event status filter for tracker and events
  app/src/androidTest/java/org/dhis2/usescases/main/MainActivityTest.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
  app/src/main/java/org/dhis2/utils/filters/StatusEventFilterHolder.java
  app/src/main/res/layout-land/fragment_program.xml
  app/src/main/res/layout/filter_status.xml
  app/src/main/res/layout/fragment_program.xml
  app/src/main/res/layout/item_program_model.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usecases/main/program/ProgramPresenterTest.kt
Labels: bug, waiting for approval

#1042 fix(DatasetTableActivity): Use of enrollment status/icons in Data sets
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/res/drawable/ic_edit_green.xml
  app/src/main/res/layout/activity_dataset_table.xml
Labels: bug, waiting for approval

#1041 fix(orgUnits): Show capture orgUnits when search ou has not been assigned in web
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.java
Labels: Ready for merge, bug

#1037 fix: handle keypad 'next' behavior on dataSet tables
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
  tableview/src/main/java/com/evrencoskun/tableview/handler/SelectionHandler.java
Labels: Ready for merge, bug
