Repository dhis2/dhis2-android-capture-app, pull requests merged in 2019-12, with the labels that each got.

#1045 fix(EnrollmentActivity): Field TEI Detail is not being saved when save without change the focus
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: Ready for merge, bug

#1047 fix(sms): Show sms permission when enabling option in settings
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerContracts.java
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java
  app/src/main/res/values/strings.xml
Labels: Ready for merge, bug

#1051 fix(maps): Fixed unregistered receiver for kujaku map downloader
  app/src/main/java/org/dhis2/App.java
Labels: bug, waiting for approval

#1048 fix(enrollent form): Removed nestedScroll in enrollment form
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/res/layout/enrollment_activity.xml
  app/src/main/res/values/strings.xml
Labels: Ready for merge, bug

#1052 fix(teiDashboard): Fixed event order
  app/src/main/java/org/dhis2/Bindings/EventExtensions.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
Labels: Ready for merge, bug

#1053 fix: Hide Save button during enrollment form loading
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/res/layout/enrollment_activity.xml
Labels: Ready for merge, bug

#1050 fix(granular sync): DataSet complete registration not been uploaded in home
  app/src/main/java/org/dhis2/data/service/SyncPresenter.java
  app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
Labels: bug, waiting for approval

#1055 fix(SearchTE): hide map when there is not selected program
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, bug

#1054 fix(rules): Transform numeric values for RuleDataValues and RuleAttributeValues
  app/src/main/java/org/dhis2/Bindings/EventExtensions.kt
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
  app/src/main/java/org/dhis2/data/forms/dataentry/EventsRuleEngineRepository.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/jira/JiraViewModel.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialog.kt
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialogModule.kt
  app/src/main/java/org/dhis2/utils/customviews/CategoryComboDialogPresenter.kt
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/main/java/org/dhis2/utils/rules/RuleEngineUtils.kt
  app/src/test/java/org/dhis2/data/forms/RulesRepositoryTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/DataValuePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/reservedValues/ReservedValuePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
  app/src/test/java/org/dhis2/utils/customviews/CategoryComboDIalogPresenterTest.kt
  app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
Labels: bug, waiting for approval

#1056 fix(dashboard): Fix crash when removing selected program in landscape dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerTabletAdapter.java
Labels: bug, waiting for approval

#1057 fix: Kujaku offline map service crashed
  app/src/main/java/org/dhis2/App.java
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/activity_search.xml
Labels: bug, waiting for approval

#1058 fix: make enrollment data visible from the start
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: bug, waiting for approval

#1059 fix(SyncManagerFragment): Remove sms toast when entering the settings screen
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
Labels: bug, waiting for approval

#1060 fix(GranularSyncPresenter): [ANDROAPP-2606] - trackerImportConflicts for a TEI are not showing
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
Labels: bug, waiting for approval

#1064 fix: not update overdue events on search screen
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: bug, waiting for approval

#1068 fix(visualDataEntry): Options that contains "-" in their name break the forms.
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageHolder.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: bug, waiting for approval

#1072 fix(OptionSet): [ANDROAPP-2616] Fix crash when dataSet has an optionSet
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
Labels: bug, waiting for approval

#1069 fix: Granular sync fixes
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
Labels: Ready for merge, bug

#1071 fix(EventCaptureRepository): [ANDROAPP-2617] Fixes order of options in an optionSet
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, bug

#1075 fix(DataValueRepository): 3 Headers CatOptionCombo DataSets
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Labels: Ready for merge, bug

#1076 fix(Fingerprint): [ANDROAPP-2621] login with fingerprint
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
Labels: bug, waiting for approval

#1074 fix(Options): [ANDROAPP-2617] - Fixes order of options in options set
  app/src/main/java/org/dhis2/utils/customviews/OptionSetPopUp.java
  app/src/main/java/org/dhis2/utils/optionset/OptionSetPresenter.kt
  app/src/test/java/org/dhis2/utils/optionset/OptionSetPresenterTest.kt
Labels: bug, waiting for approval

#1077 fix: get section by displayName
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Labels: bug

#1078 fix: Hide complete/reopen button if a dataSet cant't be edited
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: Re-review, bug, waiting for approval

#1080 feat(SMS Sync): [ANDROAPP-2629] - Disables sms sync for TEIs
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
  app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/test/java/org/dhis2/data/forms/RulesRepositoryTest.kt
  app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
Labels: Ready for merge, enhancement

#1081 fix(DataValuePresenter): Data set display option code and not the name
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/RowAction.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
Labels: Ready for merge, bug

#1084 fix(EnrollmentForm): [ANDROAPP-2631] - handles TEI coordinate field in servers 2.29 and 2.30
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: Ready for merge, bug

#1085 fix: Able to select options in Data set with can view only permissions
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerHolder.java
Labels: bug, waiting for approval

#1079 fix: DataSetInstance sync icon not being updated
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
Labels: bug, waiting for approval

#1083 fix(PeriodDialogInputPeriod): Crash in DataInputPeriod. It is not working
  app/src/main/java/org/dhis2/utils/customviews/PeriodAdapter.kt
  app/src/main/java/org/dhis2/utils/customviews/PeriodDialog.java
  app/src/main/java/org/dhis2/utils/customviews/PeriodDialogInputPeriod.java
Labels: bug, waiting for approval
