Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-06, with the labels that each got.

#1423 docs: Add information about search box with >15 options [skip ci]
  docs/src/commonmark/en/content/capture-app/new-visual-configurations.md
  docs/src/commonmark/en/content/capture-app/resources/images/options_no_search.png
  docs/src/commonmark/en/content/capture-app/resources/images/options_search.png
Labels: Documentation

#1426 feat: Create relationship featureCollection, model and layer
  app/src/androidTest/java/org/dhis2/usescases/settings/SettingsTest.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/uicomponents/map/geometry/FeatureExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/LngLatValidator.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/bound/GetBoundingBox.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/line/MapLineRelationshipToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/MapGeometryToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/TeisMapperExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapEventToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapRelationshipsToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/point/MapPointToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/mapper/MapRelationshipToRelationshipMapModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/MapStyle.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/RelationshipUiComponentModel.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewModel.java
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapEventToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapGeometryToFeatureTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapRelationshipToRelationshipMapModelTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapRelationshipsToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/bound/GetBoundingBoxTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/line/MapLineToRelationshipFeatureTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/polygon/PolygonViewModelTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/mocks/GeometryDummy.kt
  app/src/test/java/org/dhis2/uicomponents/map/mocks/RelationshipUiCompomentDummy.kt
  app/src/test/java/org/dhis2/uicomponents/map/mocks/RelationshipViewModelDummy.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
  app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
  buildsystem/dependencies.gradle
Labels: Ready for testing

#1424 feat: [ANDROAPP-2999] Adds bottomsheet behavior on ValidationRules Violation
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
  app/src/main/java/org/dhis2/utils/validationrules/ValidationResultViolationFragment.kt
  app/src/main/java/org/dhis2/utils/validationrules/ValidationResultViolationsAdapter.kt
  app/src/main/res/drawable/ic_violation_background.xml
  app/src/main/res/drawable/shadow_top.xml
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/main/res/layout/fragment_validation_result_violation.xml
  app/src/main/res/layout/violation_rules_bottom_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryTest.kt
Labels: Ready for merge, Tested, enhancement

#1428 feat: [ANDROAPP-2335] Preselect org unit when adding sequential events to a program
  app/src/main/java/org/dhis2/data/prefs/Preference.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialComponent.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenter.java
  app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1433 fix: [ANDROAPP-3104] Scrolls open section to the top of the RecyclerView
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: Ready for merge, Tested, bug

#1435 docs: Add MDM documentation in markdown format [skip ci]
  docs/src/commonmark/en/content/mdm/.A-e-miradore.md.swp
  docs/src/commonmark/en/content/mdm/.A-g-scalefusion.md.swp
  docs/src/commonmark/en/content/mdm/A-a-previous-info.md
  docs/src/commonmark/en/content/mdm/A-b-flyve.md
  docs/src/commonmark/en/content/mdm/A-c-headwind.md
  docs/src/commonmark/en/content/mdm/A-d-entgra.md
  docs/src/commonmark/en/content/mdm/A-e-miradore.md
  docs/src/commonmark/en/content/mdm/A-f-engineplus.md
  docs/src/commonmark/en/content/mdm/A-g-scalefusion.md
  docs/src/commonmark/en/content/mdm/choosing-an-mdm.md
  docs/src/commonmark/en/content/mdm/comparison-chart.md
  docs/src/commonmark/en/content/mdm/considerations.md
  docs/src/commonmark/en/content/mdm/resources/images/image1.png
  docs/src/commonmark/en/content/mdm/resources/images/image10.png
  docs/src/commonmark/en/content/mdm/resources/images/image11.png
  docs/src/commonmark/en/content/mdm/resources/images/image12.png
  docs/src/commonmark/en/content/mdm/resources/images/image13.png
  docs/src/commonmark/en/content/mdm/resources/images/image14.png
  docs/src/commonmark/en/content/mdm/resources/images/image15.png
  docs/src/commonmark/en/content/mdm/resources/images/image16.png
  docs/src/commonmark/en/content/mdm/resources/images/image2.png
  docs/src/commonmark/en/content/mdm/resources/images/image3.png
  docs/src/commonmark/en/content/mdm/resources/images/image4.png
  docs/src/commonmark/en/content/mdm/resources/images/image5.png
  docs/src/commonmark/en/content/mdm/resources/images/image6.png
  docs/src/commonmark/en/content/mdm/resources/images/image7.png
  docs/src/commonmark/en/content/mdm/resources/images/image8.png
  docs/src/commonmark/en/content/mdm/resources/images/image9.png
  docs/src/commonmark/en/dhis2_android_MDM_INDEX.md
Labels: Documentation

#1432 fix: [ANDROAPP-3093] Adds section title when there is only one section
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1434 fix: [ANDROAPP-3108] Saves datetime field without seconds in the database.
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeHolder.java
Labels: Ready for merge, Tested, bug

#1430 fix: [ANDROAPP-3109] Removes background from xml and adds it programmatically
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/res/layout/form_section.xml
Labels: Ready for testing, bug

#1437 fix: [ANDROAPP-3037] updates the complete/open status icon and label when a dataset is complete or re-open.
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
Labels: Ready for merge, Tested, bug

#1427 feat: [ANDROAPP-3090] show/hide map on relationship tab
  app/src/main/java/org/dhis2/uicomponents/map/geometry/FeatureExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/bound/GetBoundingBox.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/LayerType.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/MapStyle.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipView.kt
  app/src/main/res/drawable/map_marker.xml
  app/src/main/res/layout-land/activity_dashboard_mobile.xml
  app/src/main/res/layout/activity_dashboard_mobile.xml
  app/src/main/res/layout/fragment_relationships.xml
  app/src/test/java/org/dhis2/uicomponents/map/geometry/bound/GetBoundingBoxTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/layer/MapLayerManagerTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1441 fix: [ANDROAPP-3104] Open section scroll to top
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: Ready for merge, Tested, bug

#1422 feat: [ANDROAPP-3005] Carousel view for map display
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/java/org/dhis2/data/forms/RuleActionUnsupported.java
  app/src/main/java/org/dhis2/uicomponents/map/camera/CameraExtension.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselBinder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselRelationshipHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/ClosestPointCalculatorExtension.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/line/MapLineRelationshipToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/TeisMapperExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapRelationshipsToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/mapper/MapRelationshipToRelationshipMapModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/RelationshipUiComponentModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/TeiRelationShipsMapModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipView.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewHolder.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewModel.java
  app/src/main/java/org/dhis2/utils/ColorUtils.java
  app/src/main/res/drawable/ic_delete_forever.xml
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/form_section.xml
  app/src/main/res/layout/fragment_relationships.xml
  app/src/main/res/layout/item_carousel_relationship.xml
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_relationship.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/dhis2/uicomponents/map/geometry/ClosestPointCalculatorExtensionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapRelationshipToRelationshipMapModelTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapRelationshipsToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/mocks/RelationshipUiCompomentDummy.kt
  app/src/test/java/org/dhis2/uicomponents/map/mocks/RelationshipViewModelDummy.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1419 feat: [ANDROAPP-3010] Add overview tab to dataSets
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableComponent.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/TableCheckboxAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/TableCheckboxViewHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailComponent.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailPresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailView.kt
  app/src/main/res/drawable/round_squared_bg.xml
  app/src/main/res/drawable/rounded_square_4dp.xml
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/main/res/layout/fragment_dataset_detail.xml
  app/src/main/res/layout/item_table_checkbox.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetTable/dataSetDetail/DataSetDetailPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1418 feat: Validation Rules
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailPresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesPresenter.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesViewHolder.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailRepositoryImpl.kt
  app/src/main/java/org/dhis2/utils/customviews/AlertBottomDialog.kt
  app/src/main/java/org/dhis2/utils/validationrules/ValidationResultViolationFragment.kt
  app/src/main/java/org/dhis2/utils/validationrules/ValidationResultViolationsAdapter.kt
  app/src/main/res/drawable/ic_violation_background.xml
  app/src/main/res/drawable/shadow_top.xml
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/main/res/layout/fragment_dataset_section.xml
  app/src/main/res/layout/fragment_validation_result_violation.xml
  app/src/main/res/layout/violation_rules_bottom_sheet.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetTable/dataSetDetail/DataSetDetailPresenterTest.kt
Labels: enhancement

#1442 docs: Add internal links, fix external links, mispellings, etc [skip ci]
  docs/src/commonmark/en/content/capture-app/contribute-to-the-app.md
  docs/src/commonmark/en/content/capture-app/features-supported.md
  docs/src/commonmark/en/content/capture-app/introduction.md
  docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
  docs/src/commonmark/en/content/capture-app/new-settings.md
  docs/src/commonmark/en/content/capture-app/new-visual-configurations.md
  docs/src/commonmark/en/content/capture-app/program-indicators.md
  docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
  docs/src/commonmark/en/content/capture-app/programs-specific-features.md
  docs/src/commonmark/en/content/capture-app/recommendations-for-a-dhis2-mobile-deployment.md
  docs/src/commonmark/en/content/capture-app/value-types-supported.md
  docs/src/commonmark/en/content/implementation-guide/checklist.md
  docs/src/commonmark/en/content/implementation-guide/data-security-and-privacy.md
  docs/src/commonmark/en/content/implementation-guide/dhis2-capture-android-overview.md
  docs/src/commonmark/en/content/implementation-guide/dhis2-configuration-for-android.md
  docs/src/commonmark/en/content/implementation-guide/dhis2-server-requirements.md
  docs/src/commonmark/en/content/implementation-guide/document-map.md
  docs/src/commonmark/en/content/implementation-guide/executive-summary.md
  docs/src/commonmark/en/content/implementation-guide/installing-the-app.md
  docs/src/commonmark/en/content/implementation-guide/mobile-device-specs.md
  docs/src/commonmark/en/content/implementation-guide/rollout.md
  docs/src/commonmark/en/content/implementation-guide/scale-up.md
  docs/src/commonmark/en/content/implementation-guide/testing.md
  docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
  docs/src/commonmark/en/dhis2_android_implementation_guideline_INDEX.md
Labels: Documentation

#1451 fix: [ANDROAPP-3094] Removes the grammar red lines from option sets options
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
Labels: Ready for merge, Tested, bug

#1450 fix: [ANDROAPP-2849] Removes Long TextField dark gray color.
  app/src/main/res/values/styles.xml
Labels: Tested, bug

#1443 feat: [ANDROAPP-3088] Add dynamic layers to layers dialog
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/layout/dialog_map_layer.xml
Labels: Ready for merge, Tested, enhancement

#1454 feat: [ANDROAPP-3123] Update sync status icons
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/res/drawable/ic_filter_sync_error.xml
  app/src/main/res/drawable/ic_filter_sync_sms.xml
  app/src/main/res/drawable/ic_sync_problem_grey.xml
  app/src/main/res/drawable/ic_sync_problem_red.xml
  app/src/main/res/drawable/ic_sync_sms.xml
  app/src/main/res/drawable/ic_sync_warning.xml
Labels: Tested, enhancement

#1452 fix: [ANDROAPP-3043] update OU filter list
  app/src/main/java/org/dhis2/utils/filters/OrgUnitFilterHolder.java
Labels: Ready for merge, Tested, bug

#1449 feat: [ANDROAPP-3119] add relationships to feature collection on search screen
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
Labels: Ready for merge, Tested, enhancement

#1458 fix: [ANDROAPP-3127] update map when deleting relationship
  app/src/main/java/org/dhis2/uicomponents/map/geometry/bound/GetBoundingBox.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for testing, bug

#1456 feat: [ANDROAPP-3089] TEI card redesign
  app/src/main/java/org/dhis2/Bindings/DateExtensions.kt
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/main/res/drawable/ic_duplicate.xml
  app/src/main/res/drawable/ic_follow_up.xml
  app/src/main/res/drawable/ic_overdue.xml
  app/src/main/res/drawable/round_border_box_2.xml
  app/src/main/res/drawable/rounded_square_r2_24.xml
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_field_value.xml
  app/src/main/res/layout/item_program_model.xml
  app/src/main/res/layout/item_search_relationship_tracked_entity.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: Tested, enhancement

#1446 feat: [ANDROAPP-2979] TEI's events that have geometry are now displayed in the map.
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/uicomponents/map/geometry/FeatureExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/EventsByProgramStage.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/TeisMapperExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapRelationshipsToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeiEventsToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/LayerType.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiEventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/mapper/EventToEventUiComponent.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/EventUiComponentModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/MapStyle.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeiEventsToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/mocks/GeometryDummy.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1459 feat: [ANDROAPP-3118] Show relationship line direction
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/res/drawable/ic_arrowhead.xml
  app/src/main/res/drawable/ic_arrowhead_bidirectional.xml
Labels: Tested, enhancement

#1462 fix: [ANDROAPP-3136] Always show attribute main names in tei card
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for testing, bug

#1465 feat: [ANDROAPP-3120] link relationships with dialog and carousel on search
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/CarouselItemModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/RelationshipUiComponentModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/res/layout/item_carousel_relationship.xml
  app/src/test/java/org/dhis2/uicomponents/map/layer/MapLayerManagerTest.kt
Labels: Ready for merge, Tested, enhancement

#1464 tests: enrollment and create relationship
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/RelationshipRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
Labels: espresso test, waiting for approval

#1468 fix: [ANDROAPP-1157] Hides "complete anyways" button when dataset has set that it must be valid to complete
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
  app/src/main/res/layout/violation_rules_bottom_sheet.xml
Labels: Ready for merge, Tested, bug

#1463 feat: [ANDROAPP-3114] Extend error log info
  app/src/main/java/org/dhis2/usescases/settings/ErrorAdapter.java
  app/src/main/java/org/dhis2/usescases/settings/ErrorDialog.java
  app/src/main/java/org/dhis2/usescases/settings/ErrorViewHolder.java
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerContracts.java
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerModule.java
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerPresenter.java
  app/src/main/java/org/dhis2/usescases/settings/models/ErrorModelMapper.kt
  app/src/main/java/org/dhis2/usescases/settings/models/ErrorViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/settings/SyncManagerPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/settings/models/ErrorModelMapperTest.kt
Labels: Tested, enhancement

#1473 fix: crash search map
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapRelationshipsToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeiEventsToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonPointToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonToFeature.kt
Labels: Ready for merge, Tested

#1469 feat: [ANDROAPP-2891] Show map layer dialog in all maps
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/res/drawable/bottomsheet_bg.xml
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/dialog_map_layer.xml
  app/src/main/res/layout/fragment_relationships.xml
  app/src/main/res/layout/item_layer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Ready for testing, enhancement
