Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-10, with the labels that each got.

#1683 fix: [ANDROAPP-3388] Hide keyboard when clicking save button
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: Ready for merge, Tested, bug

#1671 fix: [ANDROAPP-3331] display attributes on carousel event card
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventViewModel.java
  app/src/main/res/layout/item_carousel_program_event.xml
Labels: Ready for merge, Tested, bug

#1679 fix: [ANDROAPP-3029] Fix tracked entity type attributes order in search
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for testing, bug

#1681 fix: [ANDROAPP-3375] Offline tei cards not showing the attributes dropdown arrow
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1684 fix: [ANDROAPP-3391] Event init takes too long when category has too many options
  app/src/main/java/org/dhis2/Bindings/CategoryOptionExtensions.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/customviews/CatOptionPopUp.kt
  app/src/test/java/org/dhis2/data/dhislogic/CategoryOptionExtensionsKtTest.kt
Labels: Ready for merge, Tested, bug

#1686 fix: [ANDROAPP-3371] Theme color prevented seeing the add event button
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt
  app/src/main/res/layout/item_stage_section.xml
  app/src/main/res/values/themes.xml
Labels: Ready for testing, bug

#1685 fix: [ANDROAPP-3409] Fix mandatory checks for ImageViewModels
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageViewModel.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
  app/src/main/java/org/dhis2/utils/customviews/FormBottomDialog.java
  app/src/main/java/org/dhis2/utils/customviews/FormBottomDialog.kt
  app/src/main/java/org/dhis2/utils/customviews/FormBottomDialogPresenter.kt
  app/src/main/res/layout/form_image.xml
  app/src/test/java/org/dhis2/data/forms/dataentry/fields/image/ImageViewModelTest.kt
  app/src/test/java/org/dhis2/utils/customviews/FormBottomDialogPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1689 fix: [Androapp 3394] Crash when parsing integer values
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/NegativeIntegerValidator.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/PositiveIntegerValidator.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/ValueTypeValidatorFactory.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/ZeroOrPositiveIntegerValidator.kt
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/test/java/org/dhis2/data/forms/dataentry/validation/NegativeIntegerValidatorTest.kt
  app/src/test/java/org/dhis2/data/forms/dataentry/validation/PositiveIntegerValidatorTest.kt
  app/src/test/java/org/dhis2/data/forms/dataentry/validation/ZeroOrPositiveIntegerValidatorTest.kt
Labels: Ready for merge, Tested, bug

#1687 fix: [ANDROAPP-3392] Adds correct hint label to search fields
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
Labels: Ready for merge, Tested, bug

#1692 fix: [ANDROAPP-3395] refactor mapManager initialization and get featureType for each layer
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/test/java/org/dhis2/uicomponents/map/layer/MapLayerManagerTest.kt
Labels: Ready for merge, Tested, bug

#1694 fix: [ANDROAPP-3431] Enables clicks on org unit field in the search activity.
  app/src/main/res/layout/custom_text_view_accent.xml
Labels: Ready for merge, Tested, bug

#1688 fix: [ANDROAPP-3079] Freeze on data entry for long forms
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
  app/src/main/res/layout/enrollment_activity.xml
  app/src/main/res/layout/section_selector_fragment.xml
Labels: Ready for merge, Tested, bug

#1695 style: [ANDROAPP-3381] Update color primary and secondary for texts
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
  app/src/main/java/org/dhis2/utils/customviews/AgeView.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
  app/src/main/java/org/dhis2/utils/customviews/OrgUnitView.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
  app/src/main/java/org/dhis2/utils/customviews/YesNoView.java
  app/src/main/res/drawable/radiobutton_color_selector.xml
  app/src/main/res/layout/activity_note_detail.xml
  app/src/main/res/layout/custom_long_text_view.xml
  app/src/main/res/layout/custom_long_text_view_accent.xml
  app/src/main/res/layout/form_section.xml
  app/src/main/res/layout/fragment_dataset_detail.xml
  app/src/main/res/layout/fragment_settings.xml
  app/src/main/res/layout/item_carousel_event.xml
  app/src/main/res/layout/item_carousel_program_event.xml
  app/src/main/res/layout/item_carousel_relationship.xml
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_error_dialog.xml
  app/src/main/res/layout/item_event.xml
  app/src/main/res/layout/item_field_value.xml
  app/src/main/res/layout/item_no_coordinates.xml
  app/src/main/res/layout/item_note.xml
  app/src/main/res/layout/item_reserved_value.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
  app/src/main/res/layout/item_setting_program.xml
  app/src/main/res/layout/item_stage_section.xml
  app/src/main/res/layout/spinner_settings_item.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: Ready for merge, Tested, design

#1697 fix: [ANDROAPP-3186] verify section layout corresponds with viewModel…
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
Labels: Ready for merge, Tested, bug

#1693 fix: [ANDROAPP-3380] Do not preselect enrollment org unit if scope is not capture
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
Labels: Ready for merge, Tested, bug

#1696 fix: [ANDROAPP-3396] Sync TEI for tracker events granular sync
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
Labels: Ready for merge, Tested, bug

#1701 fix: [ANDROAPP-3379] Check if there is an profile picture stored befo…
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepository.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryTest.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for merge, Tested, bug

#1700 fix: [ANDROAPP-3439] Text fields sending data twice
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
Labels: Ready for merge, Tested, bug

#1699 fix: [ANDROAPP-3434] Org Unit filter in dashboard now updates total filters count
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
Labels: Ready for merge, Tested, bug

#1690 [test]: ANDROAPP-3273 Update event
  app/src/androidTest/java/org/dhis2/usescases/event/EventIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt
  app/src/androidTest/java/org/dhis2/usescases/event/entity/EventStatusUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
Labels: espresso test, waiting for approval

#1704 Create INTEGER valueType validator
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/IntegerValidator.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/NumberValidator.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/ValueTypeValidatorFactory.kt
  app/src/main/java/org/dhis2/utils/ValidationUtils.kt
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/test/java/org/dhis2/data/forms/dataentry/validation/IntegerValidatorTest.kt
  app/src/test/java/org/dhis2/data/forms/dataentry/validation/NumberValidatorTest.kt
  app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
Labels: Ready for merge, Tested, bug

#1703 fix: [ANDROAPP-3395] Map not showing icons on initialization when search backdrop is active
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Ready for merge, Tested, bug

#1705 fix: [ANDROAPP-3434] update total filters
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/test/java/org/dhis2/utils/filters/FilterManagerTest.kt
Labels: Ready for merge, Tested, bug

#1708 fix [ANDROAPP-3435] align TEIs separator line
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: Ready for merge, Tested, bug

#1710 fix: [ANDROAPP-3443] Makes the icon on the date, datetime, and time fields clickable
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
Labels: Ready for merge, Tested, bug

#1706 fix: [ANDROAPP-3374] Event list should have rounded top corners
  app/src/main/java/org/dhis2/Bindings/ViewExtensions.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
Labels: Ready for merge, Tested, bug

#1707 fix: [ANDROAPP-3436] Transition of the event expand on map is not smooth
  app/src/main/java/org/dhis2/animations/ViewAnimations.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
Labels: Ready for merge, Tested, bug

#1709 fix: [ANDROAPP-3442] The X button is shown even when no data can be deleted
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
  app/src/main/java/org/dhis2/utils/customviews/FieldLayout.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
  app/src/main/java/org/dhis2/utils/customviews/YesNoView.java
Labels: Ready for merge, Tested, bug

#1714 test: [ANDROAPP-3300] Search UI test
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentTest.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/entity/DisplayListFieldsUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardIntents.kt
Labels: espresso test, waiting for approval

#1717 fix: [ANDROAPP-3447] Crash when event program has a displayInList image
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
Labels: Ready for merge, Tested, bug

#1711 fix: [ANDROAPP-3372] Cards should react when clicked
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselRelationshipHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
  app/src/main/res/layout/item_carousel_event.xml
  app/src/main/res/layout/item_carousel_program_event.xml
  app/src/main/res/layout/item_carousel_relationship.xml
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_dataset.xml
  app/src/main/res/layout/item_event.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
  app/src/main/res/layout/item_stage_section.xml
  app/src/main/res/values/colors.xml
Labels: Ready for merge, bug

#1718 fix: [ANDROAPP-3394] Remove float conversion whe storing integer values
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt
Labels: Ready for merge, Tested, bug

#1715 fix: [ANDROAPP-3299] Discrepancies between home and search screen filters
  app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/data/dhislogic/DhisProgramUtils.kt
  app/src/main/java/org/dhis2/data/dhislogic/DhisTrackedEntityInstanceUtils.kt
  app/src/main/java/org/dhis2/data/filter/DataSetFilterSearchHelper.kt
  app/src/main/java/org/dhis2/data/filter/EventProgramFilterSearchHelper.kt
  app/src/main/java/org/dhis2/data/filter/FilterController.kt
  app/src/main/java/org/dhis2/data/filter/FilterHelperActions.kt
  app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
  app/src/main/java/org/dhis2/data/filter/TrackerFilterSearchHelper.kt
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepository.kt
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModel.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramViewModelMapper.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/resources/ResourceManager.kt
  app/src/test/java/org/dhis2/data/filter/DataSetFilterSearchHelperTest.kt
  app/src/test/java/org/dhis2/data/filter/EventProgramFilterSearchHelperTest.kt
  app/src/test/java/org/dhis2/data/filter/TrackerFilterSearchHelperTest.kt
  app/src/test/java/org/dhis2/usescases/main/program/HomeRepositoryImplTest.kt
  app/src/test/java/org/dhis2/usescases/main/program/ProgramPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImplTest.kt
Labels: Ready for merge, Tested, bug

#1713 feat: [ANDROAPP-3278] show dropdown with results of orgUnits filters
  app/src/main/java/org/dhis2/data/filter/FilterPresenter.kt
  app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModule.java
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/main/MainModule.kt
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
  app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
  app/src/main/java/org/dhis2/utils/filters/OrgUnitFilterHolder.java
  app/src/main/java/org/dhis2/utils/filters/sorting/FilteredOrgUnitResult.kt
  app/src/main/res/layout/filter_org_unit.xml
  app/src/test/java/org/dhis2/usescases/main/program/HomeRepositoryImplTest.kt
Labels: Ready for merge, Tested, enhancement

#1722 fix: [ANDROAPP-3444] Adds the selected lateral bar individually to each field layout.
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerHolder.java
  app/src/main/res/layout/custom_form_coordinate.xml
  app/src/main/res/layout/custom_form_picture.xml
  app/src/main/res/layout/form_age_custom.xml
  app/src/main/res/layout/form_date_text.xml
  app/src/main/res/layout/form_date_time_text.xml
  app/src/main/res/layout/form_edit_text_custom.xml
  app/src/main/res/layout/form_option_set.xml
  app/src/main/res/layout/form_option_set_selector.xml
  app/src/main/res/layout/form_org_unit.xml
  app/src/main/res/layout/form_picture.xml
  app/src/main/res/layout/form_scan.xml
  app/src/main/res/layout/form_time_text.xml
  app/src/main/res/layout/form_yes_no.xml
Labels: Ready for merge, Tested, bug

#1649 docs: Update mobile specs to include Google
  docs/src/commonmark/en/content/implementation-guide/mobile-device-specs.md
Labels: Documentation

#1724 docs: Update SMS reporting file to link official guide [skip ci]
  docs/src/commonmark/en/content/implementation-guide/SMS-for-reporting.md
Labels: Documentation

#1726 docs: Add new tech guides with pending final location [skip ci]
  docs/src/commonmark/en/content/tech-guides/README.md
  docs/src/commonmark/en/content/tech-guides/SMS-compression.md
  docs/src/commonmark/en/content/tech-guides/resources/images/smscompression.png
Labels: Documentation

#1721 docs: add SMS to implementation guide and references [skip ci]
  docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
  docs/src/commonmark/en/dhis2_android_implementation_guideline_INDEX.md
Labels: Documentation

#1728 fix: [ANDROAPP-3443] Adds ripple effect to date, datetime, and time field's icons.
  app/src/main/res/layout/date_time_view.xml
  app/src/main/res/layout/date_time_view_accent.xml
Labels: Ready for merge, Tested, bug

#1727 [ANDROAPP-3436] Fix arrow animation in layout
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/res/layout/item_carousel_program_event.xml
Labels: Ready for merge, Tested, bug, design

#1729 fix: [ANDROAPP-3395] Fix map init
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/test/java/org/dhis2/uicomponents/map/layer/MapLayerManagerTest.kt
Labels: Tested, bug

#1725 fix: [ANDROAPP-3366] Check datavalue authority in data sets
  app/src/main/java/org/dhis2/data/dhislogic/Authorities.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryTest.kt
Labels: bug, waiting for approval

#1733 docs: Add subfolder for tech guides [skip ci]
  docs/src/commonmark/en/content/tech-guides/SMS-Sync.md
  docs/src/commonmark/en/content/tech-guides/SMS-compression.md
  docs/src/commonmark/en/content/tech-guides/resources/images/sms-compression/smscompression.png
  docs/src/commonmark/en/content/tech-guides/resources/images/sms-sync/android-sms-settings.png
  docs/src/commonmark/en/content/tech-guides/resources/images/sms-sync/compressed-sms.png
Labels: Documentation

#1723 feat: Move factory to dagger multi binding module
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/Components.java
  app/src/main/java/org/dhis2/data/dagger/ValueTypeKey.java
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/ValidatorModule.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/validation/ValueTypeValidatorFactory.kt
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: enhancement, waiting for approval

#1731 feat: [ANDROAPP-3458] Added script to label prs
  scripts/prlabels.py
Labels: Ready for testing, enhancement

#1742 fix: Reviewers script now prevents error when PR owner is different from the established developers
  scripts/reviewers.py
Labels: bug, waiting for approval

#1735 fix: Move DB import to AppTest, change RxIdling 0.11 and others
  app/build.gradle
  app/src/androidTest/java/org/dhis2/AppTest.kt
  app/src/androidTest/java/org/dhis2/Dhis2Runner.java
  app/src/androidTest/java/org/dhis2/common/di/BaseTestComponent.kt
  app/src/androidTest/java/org/dhis2/common/di/BaseTestModule.kt
  app/src/androidTest/java/org/dhis2/common/di/TestingInjector.kt
  app/src/androidTest/java/org/dhis2/common/idlingresources/DelegatingIdlingResourceScheduler.java
  app/src/androidTest/java/org/dhis2/common/idlingresources/IdlingResourceScheduler.java
  app/src/androidTest/java/org/dhis2/common/idlingresources/Rx2Idler.java
  app/src/main/java/org/dhis2/App.java
Labels: Ready for testing, bug

#1738 test: [program-event] add test cases
  app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/programevent/ProgramEventTest.kt
  app/src/androidTest/java/org/dhis2/usescases/programevent/robot/ProgramEventsRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
Labels: Ready for merge, Unit Test

#1739 fix: [Androapp 2747] Emtpy screen on recover account
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/utils/WebViewActivity.kt
  app/src/main/res/layout/activity_webview.xml
Labels: Tested, bug

#1740 fix: [ANDROAPP-3475] Sending jira issue from app is not working
  app/build.gradle
  app/src/main/java/org/dhis2/data/jira/ClickedIssueData.kt
  app/src/main/java/org/dhis2/data/jira/IssueRequest.kt
  app/src/main/java/org/dhis2/data/jira/JiraExtensions.kt
  app/src/main/java/org/dhis2/data/jira/JiraIssue.kt
  app/src/main/java/org/dhis2/data/jira/JiraIssueListRequest.kt
  app/src/main/java/org/dhis2/data/jira/JiraIssueListResponse.kt
  app/src/main/java/org/dhis2/data/jira/JiraIssuesResult.kt
  app/src/main/java/org/dhis2/data/prefs/PreferenceProviderImpl.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraActions.java
  app/src/main/java/org/dhis2/usescases/jira/JiraComponent.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraFragment.java
  app/src/main/java/org/dhis2/usescases/jira/JiraFragment.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraIssueAdapter.java
  app/src/main/java/org/dhis2/usescases/jira/JiraIssueAdapter.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraIssueHolder.java
  app/src/main/java/org/dhis2/usescases/jira/JiraIssueHolder.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraIssueService.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraModule.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraRepository.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraViewModel.kt
  app/src/main/java/org/dhis2/usescases/jira/JiraViewModelFactory.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/main/MainComponent.kt
  app/src/main/java/org/dhis2/utils/jira/IssueRequest.java
  app/src/main/java/org/dhis2/utils/jira/JiraIssue.java
  app/src/main/java/org/dhis2/utils/jira/JiraIssueField.java
  app/src/main/java/org/dhis2/utils/jira/JiraIssueListRequest.java
  app/src/main/java/org/dhis2/utils/jira/JiraIssueListResponse.java
  app/src/main/java/org/dhis2/utils/jira/OnJiraIssueClick.java
  app/src/main/java/org/dhis2/utils/jira/jiraIssueResponse.java
  app/src/main/java/org/dhis2/utils/resources/ResourceManager.kt
  app/src/main/res/layout/fragment_jira.xml
  app/src/main/res/layout/jira_issue_item.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/TestExtensions.kt
  app/src/test/java/org/dhis2/usescases/jira/JiraViewModelTest.kt
Labels: Tested, bug

#1748 docs: Update links from Google Drive to Github
  docs/src/commonmark/en/content/tech-guides/SMS-Sync.md
Labels: Documentation, waiting for approval

#1744 fix: [ANDROAPP-3480] Crash in custom text view when setting click listener
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/res/layout/custom_long_text_view_accent.xml
Labels: Tested, bug

#1745 fix: [ANDROAPP-3481] Crash due to invalid cast in DataEntryAdapter
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/SectionHandler.kt
  app/src/test/java/org/dhis2/data/forms/dataentry/SectionHandlerTest.kt
Labels: Tested, bug

#1747 feat: [ANDROAPP-3478] disable analytics in AppTest for espresso tests
  app/src/androidTest/java/org/dhis2/AppTest.kt
  app/src/main/java/org/dhis2/App.java
Labels: Tested, enhancement

#1752 fix: [ANDROAPP-2510] Allow edition of incident and enrollment date
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentFormRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentTest.kt
  app/src/main/java/org/dhis2/data/dhislogic/DhisEnrollmentUtils.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Tested, bug

#1751 feat: Use EnrollmentService access in TeiProgramListPresenter
  app/src/main/java/org/dhis2/data/dhislogic/DhisEnrollmentUtils.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenter.java
  app/src/test/java/org/dhis2/data/dhislogic/DhisEnrollmentUtilsTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenterTest.kt
  scripts/prlabels.py
Labels: Ready for testing, enhancement

#1755 fix: [ANDROAPP-3477] don't store pass if empty and catch exceptions
  app/src/main/java/org/dhis2/data/prefs/PreferenceProviderImpl.kt
Labels: Ready for merge, Tested, bug

#1750 fix: [ANDROAPP-3474] Map layer button crash and adapter init before styles
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
Labels: Internal testing, bug
