Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-08, with the labels that each got.

#1568 Tests TEI Flow enrollment
  app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teiFlow/TeiFlowRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teiFlow/TeiFlowTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teiFlow/entity/DateRegistrationUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/teiFlow/entity/EnrollmentListUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/teiFlow/entity/RegisterTEIUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
Labels: espresso test

#1570 fix: [ANDROAPP-3259] Unknown attribute crash
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for testing, bug

#1567 fix: [ANDROAPP-3258] Assign value from event to attribute
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
Labels: Ready for merge, Tested, bug

#1574 fix: [ANDROAPP-3264] Assigned values to integers showing decimals
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt
Labels: bug

#1575 fix: [ANDROAPP-3250] Missing catCombo in event initial screen
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Labels: bug

#1577 fix: [ANDROAPP-3253] Do not open activity if enrollment does not exist
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  buildsystem/dependencies.gradle
Labels: bug

#1582 fix: [ANDROAPP-3160] Fix landscape dashboard pages titles
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
Labels: bug, waiting for approval

#1586 fix: [ANDROAPP-3275] Indicator name is not always displayed
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt
Labels: bug, waiting for approval

#1585 fix: [ANDROAPP-2669] Update drawable tint when changing program
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_search.xml
Labels: bug, waiting for approval

#1588 test: Event see, share and delete
  app/src/androidTest/java/org/dhis2/common/matchers/CommonMatchers.kt
  app/src/androidTest/java/org/dhis2/usescases/event/EventIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt
  app/src/androidTest/java/org/dhis2/usescases/event/entity/EventDetailsUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/event/entity/TEIProgramStagesUIModel.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/java/org/dhis2/utils/customviews/CircularCompletionView.java
  app/src/main/res/layout/activity_event_initial.xml
Labels: espresso test, waiting for approval

#1589 fix: [ANDROAPP-3116] Notes badge color
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/res/values/colors.xml
Labels: bug, waiting for approval

#1587 fix: [ANDROAPP-3276] Hide schedule option if hideDueDate is true
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
Labels: bug, waiting for approval

#1590 feat: [ANDROAPP-3086] QR and Barcode allow typing
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextRow.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/res/layout/scan_text_view.xml
  app/src/main/res/layout/scan_text_view_accent.xml
Labels: Tested, enhancement, waiting for approval

#1584 fix: [ANDROAPP-3095] Dismiss popup when item is selected
  app/src/main/java/org/dhis2/utils/customviews/OptionSetPopUp.java
Labels: bug, waiting for approval

#1595 fix: [ANDROAPP-3274] Prevents user's ability to add an enrollment when doing an empty search
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1596 fix: [ANDROAPP-3086] QR and Barcode crash inputting text in the search attribute field
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
Labels: bug, waiting for approval

#1598 fix: [ANDROAPP-3296] Org Unit selection when scrolling in the orgUnitSelector tree.
  app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorAdapter.java
  app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorHolder.kt
Labels: Tested, bug

#1583 fix: [ANDROAPP-3033] Open next section if current selections is hidden
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/GetNextVisibleSection.kt
  app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
Labels: Ready for merge, Tested, bug

#1594 fix: [ANDROAPP-3287] handles correct selection when scrolling in the sync error log
  app/src/main/java/org/dhis2/usescases/settings/ErrorAdapter.java
  app/src/main/java/org/dhis2/usescases/settings/ErrorViewHolder.java
  app/src/main/java/org/dhis2/usescases/settings/models/ErrorViewModel.kt
Labels: Ready for merge, Tested, bug

#1592 fix: Multiple unnecessary network calls in search screen
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Tested

#1593 fix: [ANDROAPP-3232] Changing Event date clear OrgUnit field
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
Labels: Tested, bug
