Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-12, with the labels that each got.

#1806 feat: [ANDROAPP-3453] (Maps) don't move camera to enrollment
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
Labels: Ready for merge, Tested, enhancement

#1814 fix: [ANDROAPP-3019] org unit of existing event not editable
  app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
Labels: Ready for merge, Tested, bug

#1803 fix: [ANDROAPP-3466] display device position on maps
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
Labels: Ready for merge, Tested, bug

#1812 fix: [ANDROAPP-1153] category options restricted by orgUnits
  app/src/main/java/org/dhis2/Bindings/CategoryOptionExtensions.kt
  app/src/main/java/org/dhis2/data/dhislogic/CategoryOptionExtensions.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/customviews/CatOptionPopUp.kt
  app/src/test/java/org/dhis2/data/dhislogic/CategoryOptionExtensionsKtTest.kt
Labels: Ready for merge, Tested, bug

#1815 fix: [ANDROAPP-3551] add all relationships to featureCollections
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
Labels: Ready for merge, Tested, bug

#1784 test: [ANDROAPP-3490] fix map ui test
  app/src/androidTest/java/org/dhis2/common/idlingresources/MapIdlingResource.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTEIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
Labels: Ready for testing, Unit Test

#1816 fix: [ANDROAPP-3561] Assigned to me filter is not displayed in tracker programs
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, bug

#1819 fix: [ANDROAPP-3553] handle image when TEI is not downloaded
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, bug

#1818 fix: [ANDROAPP-3538] Stage access is not set properly at event creation
  app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1820 fix: Crash date field and focus enabling/disable in edit text
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/YesNoView.java
  app/src/main/res/layout/form_edit_text_custom.xml
Labels: bug, waiting for approval

#1817 feat: [ANDROAPP-3539] Retrieve EventLineList from SDK
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/BaseChartRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/BaseRepository.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ChartsRepositoryImplTest.kt
Labels: Ready for merge, Tested, enhancement

#1824 feat: add toggle view to RadioButtonViewModel
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/res/layout/form_toggle.xml
Labels: Ready for testing, enhancement

#1825 fix: [ANDROAPP-3557] use frameLayout params to render options
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/VisualOptionSetView.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
  app/src/test/java/org/dhis2/utils/granularsync/GranularSyncPresenterTest.kt
  app/src/test/java/org/dhis2/utils/optionset/OptionSetPresenterTest.kt
Labels: Ready for testing, bug

#1826 fix: Add Custom Binding Adapter
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/YesNoView.java
  app/src/main/res/layout/form_check_button.xml
  app/src/main/res/layout/form_radio_button_horizontal.xml
Labels: bug, waiting for approval

#1829 fix: [ANDROAPP-3571] hide sync state icon creating relationship
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.kt
Labels: Ready for merge, Tested, bug

#1828 feat: [ANDROAPP-3514] add BottomNavigation to home
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_program.xml
Labels: Ready for merge, Tested, enhancement

#1835 fix: [ANDROAPP-3516] update color of bottomNavigation
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
Labels: Ready for merge, Tested, bug

#1836 fix: [ANDROAPP-3575] ScanView crashed when error was null
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1833 feat: [ANDROAPP-3465] Removes google play services - Dialog removal
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/utils/NetworkUtils.java
Labels: Ready for merge, Tested, enhancement

#1831 fix: [ANDROAPP-3566] Reserved value refill
  app/src/androidTest/java/org/dhis2/usescases/settings/SettingsRobot.kt
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/data/schedulers/SchedulerProvider.java
  app/src/main/java/org/dhis2/data/schedulers/SchedulerProvider.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueActivity.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueAdapter.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueAdapter.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueContracts.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueMapper.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueModel.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueModel.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueModule.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValuePresenter.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueRepository.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueRepository.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueView.kt
  app/src/main/java/org/dhis2/usescases/reservedValue/ReservedValueViewHolder.java
  app/src/main/res/layout/item_reserved_value.xml
  app/src/test/java/org/dhis2/usescases/reservedValues/ReservedValuePresenterTest.kt
Labels: Internal testing, bug
