Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-02, with the labels that each got.

#1169 fix: [ANDROAPP-1670] Updated search activity to be able to use QR/Barcode scanner
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchProgramAttributes.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
Labels: Ready for merge, Tested

#1161 test: Migrating Indicators to kotlin and Unit test
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsComponent.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsComponent.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsModule.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsView.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterTest.kt
Labels: Ready for merge, Unit Test

#1172 fix(SearchActivity): [ANDROAPP-2728] handle the location permision on the search activity
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Ready for merge, bug

#1174 fix: [Androapp 1670] QR in search screen
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchProgramAttributes.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/usescases/splash/SplashModule.kt
Labels: Ready for merge, bug

#1175 fix: [ANDROAPP-2726] fields recalculate when receiving the gallery or camera intent result.
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for merge, bug

#1173 fix: [ANDROAPP-2724] Catch exception when relationship object is incomplete
  app/src/main/java/org/dhis2/AppModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipView.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipViewHolder.java
  app/src/main/java/org/dhis2/utils/resources/ResourceManager.kt
  app/src/main/res/layout/item_relationship.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipPresenterTest.kt
Labels: Tested, bug, waiting for approval

#1176 fix: [ANDROAPP-2727] Fixed loop in event form after completing the event
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, bug

#1168 fix: [ANDROAPP-2672] Update notes layout with final design
  app/build.gradle
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/Bindings/EditTextExtensions.kt
  app/src/main/java/org/dhis2/Bindings/StringExtensions.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/notes/NotesFragment.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesRepository.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesViewHolder.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailActivity.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
  app/src/main/res/layout/activity_note_detail.xml
  app/src/main/res/layout/fragment_notes.xml
  app/src/main/res/layout/item_note.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1179 fix: [ANDROAPP-2660] Correct sort order the searchable fields
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for merge, bug

#1180 feat: [ANDROAPP-2713] Apply "Assigned to me" filter in search screen
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, enhancement

#1181 feat: [ANDROAPP-2712] apply "Assigned to me" filter in event screen
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1183 fix: [ANDROAPP-2687] orgUnit tree activity appears several times
  app/src/main/java/org/dhis2/data/user/UserComponent.java
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.java
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeComponent.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeModule.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreePresenter.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeRepository.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/layout/ou_tree_activity.xml
  app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/orgunitselector/OUTreeRepositoryTest.kt
Labels: bug, waiting for approval

#1185 fix: [ANDROAPP-2740] crash in relationship
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerTabletAdapter.java
Labels: Ready for merge, Tested, bug

#1184 feat: [ANDROAPP-7231] Changes save button to a FAB button
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/res/layout/enrollment_activity.xml
Labels: Ready for merge, Tested, enhancement

#1189 feat: [ANRDROAPP-2733] Change form alerts design to bottomSheetDialogs
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/utils/customviews/AlertBottomDialog.kt
  app/src/main/res/layout/alert_bottom_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for testing, enhancement

#1194 fix: [ANDROAPP-2725] optionSet with images total count for percentage
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, bug

#1193 fix: [Androapp-2745] Note edition should always be on top of save button
  app/src/main/res/layout/activity_note_detail.xml
Labels: Tested, bug, waiting for approval

#1188 fix: [ANDROAPP-2737] Value on a text field is saved when dismissing the Keyboard
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/utils/customviews/TextInputAutoCompleteTextView.java
  app/src/main/res/layout/enrollment_activity.xml
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for merge, Tested, bug

#1190 fix: [ANDROAPP-2728] Updates dashboard if an enrollment's attribute that is displayed is updated
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/main/java/org/dhis2/utils/OrientationUtils.kt
Labels: Ready for testing, Tested, bug

#1192 fix: [ANDROAPP-2734/35] Program rules fixes
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt
Labels: Tested, bug

#1197 fix: [ANDROAPP-1670] scan not capturing data on search and check rendering type
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
Labels: Ready for merge, bug

#1198 fix: [ANDROAPP-2732] Fix image height for sequential and matrix rendering
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageRow.java
  app/src/main/res/layout/section_selector_fragment.xml
Labels: Ready for merge, bug

#1201 fix: [ANDROAPP-2716] increase row header width when clicking zoom icon
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
  tableview/src/main/java/com/evrencoskun/tableview/TableView.java
Labels: Ready for merge, bug

#1199 fix: [ANDROAPP-2743] Grey out data sets when "Assigned to me" filter is active
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModule.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramPresenter.kt
  app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
  app/src/test/java/org/dhis2/usescases/main/program/HomeRepositoryImplTest.kt
Labels: Ready for merge

#1204 fix: [ANDROAPP-2772] Fix loop with program rules action assign and error
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
Labels: Tested
