Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-04, with the labels that each got.

#1303 feat: [ANDROAPP-2861,ANDROAPP-2862] Update SDK to support SMS in tracker
  app/build.gradle
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
  app/src/main/java/org/dhis2/usescases/sync/SyncActivity.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncContracts.kt
  app/src/main/java/org/dhis2/utils/granularsync/GranularSyncPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/form_spinner.xml
  app/src/main/res/layout/form_spinner_accent.xml
  app/src/main/res/layout/item_program_model.xml
  app/src/main/res/values/styles.xml
Labels: enhancement, waiting for approval

#1311 test: [ANDROAPP-2569] Unit test to DatasetTable Repository
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryTest.kt
Labels: Unit Test, waiting for approval

#1322 fix: [ANDROAPP-2874] Fix enrollment from tei dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
Labels: bug, waiting for approval

#1323 fix: [ANDROAPP-2876] Icons overlap in search screen
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: bug, waiting for approval

#1319 fix: [ANDROAPP-2857] Display color and icon for stages and dataSets
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/main/res/layout/activity_event_initial.xml
Labels: Tested, bug

#1317 fix: [ANDROAPP-2858] Fixes the search displayFrontPage and minimum required attribute
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Tested, bug

#1321 fix: [ANDROAPP-2875] Handle single event deletion
  app/src/main/java/org/dhis2/usescases/main/program/HomeRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
Labels: Tested, bug

#1316 fix: [ANDROAPP-2701] Fixes fab menu items' shadow.
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
Labels: Tested, bug

#1313 fix: [ANDROAPP-2696] Remove underline from EditText in the OrgUnit filter layout
  app/src/main/res/layout/filter_org_unit.xml
Labels: Tested, bug

#1325 fix: [ANDROAPP-2879] clear focus when orientation changes
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
Labels: Ready for merge, bug

#1324 fix: [ANDROAPP-2885] Filters in maps do not update data
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/maps/MapLayerDialog.kt
  app/src/main/java/org/dhis2/utils/maps/MapLayerManager.kt
  app/src/main/res/layout/dialog_map_layer.xml
  app/src/main/res/values/strings.xml
Labels: Tested, bug, waiting for approval

#1326 fix: Use code for option set fix
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
Labels: Ready for merge, Tested, bug

#1320 test: [ANDROAPP-2571] unit test on DataValueRepository and migration to kotlin
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryTest.kt
Labels: Unit Test

#1314 fix: [ANDROAPP-2859] value type icon white on TEI search
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: Ready for merge, Tested, bug

#1312 fix: [ANDROAPP-2871] enrollment errors only when save button is clicked
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
Labels: Ready for merge, Tested, bug

#1330 fix: bug when trying to sync tei
  app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
  app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
Labels: Ready for merge, Tested, bug

#1298 fix: [ANDROAPP-2853] Downloading message in search shown several times
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1334 fix: [ANDROAPP-2860] value not null deleting image
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
Labels: Ready for testing, bug

#1333 fix: [ANDROAPP-2895] Attribute not downloaded causing crashes
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Tested, bug

#1338 fix: [ANDROAPP-2898] Always show arrows in sections
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
Labels: Tested, bug

#1337 fix: [ANDROAPP-2879] Fix rotation displacement of cells
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  tableview/src/main/java/com/evrencoskun/tableview/TableView.java
Labels: bug, waiting for approval

#1341 fix: [ANDROAPP-2900] info icon to wrap_content
  app/src/main/res/layout/item_dataset_row.xml
Labels: Ready for merge, Tested, bug

#1339 fix: [ANDROAPP-2709] Round corners for program and program stage icons
  app/src/main/java/org/dhis2/usescases/main/program/ProgramModelHolder.kt
  app/src/main/res/layout/activity_event_initial.xml
  app/src/main/res/layout/item_program_model.xml
Labels: Ready for merge, Tested, bug

#1342 fix: [ANDROAPP-2902] TEI item list layout when attributes are not shown.
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: Ready for merge, Tested, bug

#1344 fix: [ANDROAPP-2903] Enrollment form not opening when creating a tei for relationship
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
Labels: Tested, bug

#1345 fix: [ANDROAPP-2904] Fixes QR Code Scan for the first time
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1346 fix: [ANDROAPP-2703] sort indicators alphabetically
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
Labels: Ready for merge, Tested, bug

#1343 fix: [ANDROAPP-2901] set coordinateView when request permission
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
Labels: Ready for merge, Tested, bug

#1349 fix: [ANDROAPP-2908] Separates Scan code reader depending on its ValueTypeRenderingType
  app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
Labels: Tested, bug

#1353 fix: [ANDROAPP-2915] Adds ellipsis to the end of the stage display name
  app/src/main/res/layout/item_stage_section.xml
Labels: Tested, bug

#1355 fix: [ANDROAPP-2913] update fields after reopen event
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1354 fix: [ANDROAPP-2916] Last section padding/shadow fix
  app/src/main/java/org/dhis2/Bindings/Extensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/utils/customviews/ImageDetailBottomDialog.kt
  app/src/main/res/drawable/shadow.xml
  app/src/main/res/layout/form_section.xml
Labels: Ready for merge, Tested, bug

#1352 fix: [ANDROAPP-2914] Looping rules message displayed when hiding attribute from event
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
  app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
Labels: Ready for testing, bug

#1356 fix: [ANDROAPP-2921] Pin dialog shoud close session if clicked on forgot code
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
  app/src/main/java/org/dhis2/utils/session/PinDialog.kt
  app/src/main/java/org/dhis2/utils/session/PinModule.kt
  app/src/main/java/org/dhis2/utils/session/PinPresenter.kt
  app/src/test/java/org/dhis2/utils/session/PinPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1358 fix: [ANDROAPP-2922] Show assign to me filter only if a program stage is configured
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1359 fix: Crash on search initialization when results come before setting trackedEntityType
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: bug

#1374 fix: [ANDROAPP-2980] change save icon
  app/src/main/res/layout/enrollment_activity.xml
  app/src/main/res/layout/section_selector_fragment.xml
Labels: Ready for merge, Tested, bug
