Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-11, with the labels that each got.

#1756 feat: [ANDROAPP-2978] Display coordinates data elements in maps
  app/build.gradle
  app/src/main/java/org/dhis2/data/dhislogic/DhisMapUtils.kt
  app/src/main/java/org/dhis2/uicomponents/map/TeiMarkers.kt
  app/src/main/java/org/dhis2/uicomponents/map/camera/CameraExtension.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/FeatureProperties.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/MapGeometryToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapDataElementToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapEventToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/BaseMap.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/BaseMapHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/BaseMapType.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/BasemapAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/LayerType.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/DataElementMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiEventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapData.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/TrackerMapData.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewModel.kt
  app/src/main/java/org/dhis2/utils/resources/ResourceManager.kt
  app/src/main/res/drawable/ic_heatmap_icon.xml
  app/src/main/res/drawable/ic_image_poi.xml
  app/src/main/res/drawable/map_marker.xml
  app/src/main/res/drawable/satellite_map_preview.png
  app/src/main/res/drawable/street_map_preview.png
  app/src/main/res/layout/basemap_item.xml
  app/src/main/res/layout/dialog_map_layer.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapDataElementToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapEventToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapGeometryToFeatureTest.kt
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1757 fix: [ANDROAPP-3433] change database format for DateTime fields
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
  app/src/main/java/org/dhis2/utils/DateUtils.java
Labels: Ready for merge, Tested, bug

#1762 fix: [ANDROAPP-2747] Fix submit recover address button feedback
  app/src/main/java/org/dhis2/utils/WebViewActivity.kt
Labels: Ready for merge, Tested, bug

#1753 test: [ANDROAPP-3490] Adds idlingResource to get map features for ui testing.
  app/src/androidTest/java/org/dhis2/common/idlingresources/MapIdlingResource.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
  app/src/main/assets/paperwork.json
Labels: Unit Test, waiting for approval

#1759 feat: [ANDROAPP-3484] Analytics module
  app/build.gradle
  app/src/main/java/org/dhis2/data/server/ServerComponent.java
  app/src/main/java/org/dhis2/data/server/ServerModule.java
  app/src/main/java/org/dhis2/data/server/ServerModule.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsModule.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterTest.kt
  dhis_android_analytics/.gitignore
  dhis_android_analytics/build.gradle
  dhis_android_analytics/consumer-rules.pro
  dhis_android_analytics/proguard-rules.pro
  dhis_android_analytics/src/main/AndroidManifest.xml
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/Charts.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepository.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/DhisAnalyticCharts.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
  settings.gradle
Labels: enhancement, waiting for approval

#1764 fix: map ui test
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
Labels: Ready for testing, bug

#1760 fix: [ANDROAPP-3496] enrollment from-to filter
  app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
Labels: Ready for merge, Tested, bug

#1766 feat: Update develop with 2.3.1 changes
  app/src/androidTest/java/org/dhis2/AppTest.kt
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/SectionHandler.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
  app/src/main/java/org/dhis2/data/prefs/PreferenceProviderImpl.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/main/res/layout/custom_long_text_view_accent.xml
  app/src/test/java/org/dhis2/data/forms/dataentry/SectionHandlerTest.kt
  docs/src/commonmark/en/content/capture-app/recommendations-for-a-dhis2-mobile-deployment.md
  docs/src/commonmark/en/content/tech-guides/README.md
  docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
  docs/src/commonmark/en/dhis2_android_implementation_guideline_INDEX.md
Labels: enhancement, waiting for approval

#1761 feat: [ANDROAPP-3506] EventService: use canCreateEventInEnrollment sdk method
  app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewModel.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt
Labels: Ready for merge, Tested, enhancement

#1765 fix: [ANDROAPP-3498] IndexOutOfBounds in dataEntryAdapter when checking section header
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
Labels: Ready for merge, Tested, bug

#1758 feat: [ANDROAPP-2893] Show coordinate attributes in maps
  app/src/main/java/org/dhis2/data/dhislogic/DhisMapUtils.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/MapGeometryToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/feature/MapCoordinateFieldToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapAttributeToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapCoordinateFieldToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapDataElementToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapDataElementToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapEventToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/LayerType.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/FieldMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModelExtensions.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapCoordinateFieldToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapEventToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapGeometryToFeatureTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapAttributeToFeatureTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapDataElementToFeatureTest.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: enhancement, waiting for approval

#1770 fix: [ANDROAPP-3492] apply set mandatory for matrix/sequential render…
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
Labels: Ready for testing, bug

#1763 fix: [ANDROAPP-3501] display TEIs on map when creating new relationship
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
Labels: bug, waiting for approval

#1775 fix: [ANDROAPP-3303] Hide close filters arrow in landscape search screen
  app/src/main/res/layout-land/activity_search.xml
Labels: Ready for testing, bug

#1769 feat: [ANDROAPP-3495] Disable matomo in debug mode
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
Labels: enhancement, waiting for approval

#1778 feat: last 2.3.1 changes
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapEventToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/featurecollection/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
  app/src/main/res/layout-land/activity_search.xml
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapEventToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
Labels: enhancement, waiting for approval

#1768 fix: [ANDROAPP-3280] from-to filter not showing pre selected dates on…
  app/src/androidTest/java/org/dhis2/common/filters/FiltersRobot.kt
  app/src/androidTest/java/org/dhis2/common/matchers/DatePickerMatchers.kt
  app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/main/java/org/dhis2/utils/filters/FilterHolder.java
  app/src/main/res/layout/activity_main.xml
Labels: Ready for merge, Tested, bug

#1776 fix: [ANDROAPP-2986] Long text cells require long click
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
  tableview/src/main/java/com/evrencoskun/tableview/adapter/recyclerview/holder/AbstractViewHolder.java
  tableview/src/main/java/com/evrencoskun/tableview/listener/itemclick/CellRecyclerViewItemClickListener.java
Labels: Ready for merge, Tested, bug

#1772 feat: [Androapp-3502] Remove crashlytics dependencies
  app/build.gradle
  app/com.crashlytics.settings.json
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/java/org/dhis2/utils/reporting/CrashReportController.kt
  app/src/main/java/org/dhis2/utils/reporting/CrashReportControllerImpl.kt
  app/src/main/java/org/dhis2/utils/reporting/CrashReportModule.kt
  app/src/main/java/org/dhis2/utils/timber/ReleaseTree.java
  build.gradle
  buildsystem/dependencies.gradle
Labels: Ready for merge, Tested, enhancement

#1774 test: [ANDROAPP-3455] Filter and sort test
  app/src/androidTest/java/org/dhis2/common/matchers/RecyclerviewMatchers.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTEIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/robot/FilterRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/utils/filters/FilterHolder.java
  app/src/main/res/layout/activity_search.xml
Labels: Unit Test

#1767 feat: [ANDROAPP-3485] Repositories for charts
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsView.kt
  app/src/main/res/layout/fragment_indicators.xml
  dhis_android_analytics/build.gradle
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/BaseChartRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/BaseRepository.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/Charts.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepository.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/DhisAnalyticCharts.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/formatters/DateLabelFormatter.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntry.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineData.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ChartsRepositoryImplTest.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/data/GraphTest.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntryTest.kt
Labels: enhancement, waiting for approval

#1773 feat: [ANDROAPP-3464] Create extra matomo tracker for implementations
  app/src/androidTest/java/org/dhis2/AppTest.kt
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/data/server/ServerModule.kt
  app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
  app/src/main/java/org/dhis2/data/service/SyncPresenter.java
  app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
  app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsController.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsModule.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/TrackerController.kt
  app/src/main/res/layout/development_activity.xml
Labels: Ready for merge, Tested, enhancement

#1771 fix: [ANDROAPP-3503] Open form/event initial screen when setting date to schedule event
  app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventActivity.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventContract.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventModule.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventPresenterImpl.kt
  app/src/test/java/org/dhis2/usescases/events/ScheduledEventPresenterImplTest.kt
Labels: Ready for merge, Tested, bug

#1777 feat: [ANDROAPP-3483] add chartView to recyclerview
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/IndicatorsRobot.kt
  app/src/main/java/org/dhis2/data/analytics/AnalyticsModel.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/AnalyticsAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/ChartViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/SectionTitleViewHolder.kt
  app/src/main/res/layout/fragment_indicators.xml
  app/src/main/res/layout/item_chart.xml
  app/src/main/res/layout/item_section_tittle.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, waiting for approval

#1779 fix: [ANDROAPP-3511] handle null catOptionCombo
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
Labels: Ready for testing, bug

#1780 feat: [ANDROAPP-3460] Use new analytics features in IndicatorPresenter
  app/src/androidTest/java/org/dhis2/common/matchers/ChartMatchers.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/AnalyticsRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/IndicatorsRobot.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/data/analytics/AnalyticsModel.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/AnalyticsAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/ChartViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsView.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/SectionTitleViewHolder.kt
  app/src/main/res/layout-land/activity_search.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterTest.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/BaseChartRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/BaseRepository.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/Charts.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepository.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/DhisAnalyticCharts.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/formatters/DateLabelFormatter.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntry.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineChart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToLineData.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/ChartsRepositoryImplTest.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/data/GraphTest.kt
  dhis_android_analytics/src/test/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToEntryTest.kt
Labels: Internal testing, enhancement

#1782 fix: [ANDROAPP-3520] update constraint-layout library
  app/build.gradle
Labels: Tested, bug

#1781 fix: [ANDROAPP-3519] set editText max height for longtext dialog
  app/src/main/res/layout/dialog_edittext.xml
Labels: Ready for testing, bug

#1783 feat: last changes in 2.3.1
  app/build.gradle
  app/src/androidTest/java/org/dhis2/common/filters/FiltersRobot.kt
  app/src/androidTest/java/org/dhis2/common/matchers/DatePickerMatchers.kt
  app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
  app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventActivity.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventContract.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventModule.kt
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_edittext.xml
  app/src/test/java/org/dhis2/usescases/events/ScheduledEventPresenterImplTest.kt
  tableview/src/main/java/com/evrencoskun/tableview/adapter/recyclerview/holder/AbstractViewHolder.java
  tableview/src/main/java/com/evrencoskun/tableview/listener/itemclick/CellRecyclerViewItemClickListener.java
Labels: enhancement, waiting for approval

#1785 test: [ANDROAPP-3512] Mix Search and Filter test
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/robot/FilterRobot.kt
Labels: Unit Test, waiting for approval

#1796 feat: [Androapp-3471] formview
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentFormRobot.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolderFactory.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitRow.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureRow.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/ActivityResultObservable.kt
  app/src/main/java/org/dhis2/utils/ActivityResultObserver.kt
  app/src/main/java/org/dhis2/utils/customviews/OrgUnitView.java
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/res/layout/custom_form_coordinate.xml
  app/src/main/res/layout/enrollment_activity.xml
  app/src/main/res/layout/view_form.xml
Labels: enhancement

#1789 refactor: [ANDROAPP-3471] move customview actions to viewModel
  app/src/main/java/org/dhis2/Bindings/ViewExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetSelectionView.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/res/layout/custom_form_picture.xml
  app/src/main/res/layout/form_edit_text_custom.xml
  app/src/main/res/layout/form_option_set.xml
  app/src/main/res/layout/form_option_set_selector.xml
  app/src/main/res/layout/form_org_unit.xml
  app/src/main/res/layout/form_scan.xml
Labels: refactor

#1787 fix: [ANDROAPP-3522] Maps not rendering when TEType has no icon
  app/src/main/java/org/dhis2/uicomponents/map/model/EventUiComponentModel.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
Labels: Ready for merge, Tested, bug

#1795 fix: [ANDROAPP-3533] Incorrect placement of the filter indicator in home screen
  app/src/main/res/layout/activity_main.xml
Labels: Ready for merge, Tested, bug

#1791 refactor: [ANDROAPP-3471] Refactors RadioButtonHolder and YesNoView
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/java/org/dhis2/utils/customviews/YesNoView.java
  app/src/main/res/layout/form_yes_no.xml
Labels: refactor

#1802 refactor: SectionHolder
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactory.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolderFactory.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionView.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
  app/src/main/java/org/dhis2/utils/recyclers/StickyHeaderItemDecoration.kt
  app/src/main/res/layout/form_section.xml
  app/src/main/res/layout/section_view.xml
  app/src/test/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModelTest.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
  app/src/test/java/org/dhis2/utils/customviews/FormBottomDialogPresenterTest.kt
Labels: refactor, waiting for approval

#1788 fix: [ANDROAPP-3525] Percentage icon set in wrong fields
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: Ready for merge, Tested, bug

#1794 fix: [ANDROAPP-3534] Unable to type in text fields in data set
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
Labels: Ready for merge, Tested, bug

#1798 refactor: [ANDROAPP-3471] display view
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageViewModel.java
  app/src/main/java/org/dhis2/utils/customviews/DisplayCustomView.kt
  app/src/main/java/org/dhis2/utils/customviews/ImageCustomView.kt
  app/src/main/java/org/dhis2/utils/recyclers/StickyHeaderItemDecoration.kt
  app/src/main/res/layout/custom_form_display.xml
  app/src/main/res/layout/custom_form_image.xml
  app/src/main/res/layout/form_image.xml
Labels: refactor

#1793 test: [ANDROAPP-3524] create TEI and check enrollment
  app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/searchFlow/SearchFlowTest.kt
Labels: Unit Test

#1797 fix: [ANDROAPP-3535] Add all data approval states to check
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryTest.kt
Labels: Internal testing, bug

#1790 fix: [ADROAPP-3529] Widget not rendering correct icon
  app/src/main/java/org/dhis2/Bindings/Extensions.kt
  app/src/main/java/org/dhis2/widgets/DhisCustomLauncher.kt
Labels: Internal testing, bug

#1786 feat: [ANDROAPP-3513] Navigation bar
  app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
  app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
  app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBarAnimations.kt
  app/src/main/res/drawable/ic_navigation_analytics.xml
  app/src/main/res/drawable/ic_navigation_details.xml
  app/src/main/res/drawable/ic_navigation_events.xml
  app/src/main/res/drawable/ic_navigation_forms.xml
  app/src/main/res/drawable/ic_navigation_list_view.xml
  app/src/main/res/drawable/ic_navigation_map_view.xml
  app/src/main/res/drawable/ic_navigation_notes.xml
  app/src/main/res/drawable/ic_navigation_relationships.xml
  app/src/main/res/drawable/ic_navigation_table_view.xml
  app/src/main/res/drawable/ic_navigation_tasks.xml
  app/src/main/res/drawable/ic_navigation_tei_detail.xml
  app/src/main/res/drawable/navigation_item_selector.xml
  app/src/main/res/layout/development_activity.xml
  app/src/main/res/menu/navigation_dashboard_menu.xml
  app/src/main/res/menu/navigation_form_menu.xml
  app/src/main/res/menu/navigation_home_menu.xml
  app/src/main/res/menu/navigation_search_menu.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: Ready for merge, Tested, enhancement

#1801 fix: [ANDROAPP-3532] Set url after scanning QR
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
Labels: Ready for merge, Tested, bug

#1800 refactor: [ANDROAPP-3465] remove play services
  app/build.gradle
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/data/location/LocationModule.kt
  app/src/main/java/org/dhis2/data/location/LocationProvider.kt
  app/src/main/java/org/dhis2/data/location/LocationProviderImpl.kt
  app/src/main/java/org/dhis2/data/notifications/DhisFirebaseMessagingService.kt
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, refactor

#1808 feat: [ANDROAPP-3537] Image view component
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactory.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageCustomView.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/image/ImageViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/MatrixOptionSetModel.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/VisualOptionSetView.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageHolder.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventFieldMapper.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/customviews/FormBottomDialogPresenter.kt
  app/src/main/res/layout/custom_form_image.xml
  app/src/main/res/layout/form_image.xml
  app/src/main/res/layout/matrix_option_set.xml
  app/src/test/java/org/dhis2/data/forms/dataentry/fields/image/ImageViewModelTest.kt
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
  app/src/test/java/org/dhis2/utils/customviews/FormBottomDialogPresenterTest.kt
Labels: enhancement, waiting for approval

#1809 fix: Avoid setting error twice and deleting edit text when re-binding happens
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentFormRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/enrollment/EnrollmentTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EnrollmentRobot.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateView.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorViewHolder.kt
Labels: Ready for testing, bug

#1813 test: [ANDROAPP-3512] Fix overdue filter test
  app/src/androidTest/java/org/dhis2/usescases/flow/teiFlow/TeiFlowRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
Labels: Unit Test
