Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-05, with the labels that each got.

#1369 fix(EnrollmentActivity): [ANDROAPP-2982] check uuid is not null
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/res/values/strings.xml
Labels: Tested, bug

#1372 fix: [ANDROAPP-2668] Support RTL in dataSet tables
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  app/src/main/res/drawable/ic_arrow_back.xml
  app/src/main/res/drawable/ic_increase_width.xml
  app/src/main/res/drawable/ic_reduce_width.xml
  tableview/build.gradle
  tableview/src/main/java/com/evrencoskun/tableview/TableView.java
Labels: Tested, bug

#1373 fix: [ANDROAPP-2981] Show section number
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/res/layout/form_section.xml
Labels: Tested, bug

#1371 fix: [ANDROAPP-2983] Fix crash on ProgramEventDetailRepository
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventMapperTest.kt
Labels: Tested, bug

#1375 fix: [ANDROAPP-2666] RTL errors in tei dashboard card
  app/src/main/res/layout/fragment_tei_data_card_front.xml
Labels: Tested, bug

#1365 fix: [ANDROAPP-2954] Sync screen showing after login offline
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1370 fix: [ANDROAPP-2984] Crash when using fingerprint
  app/build.gradle
  app/src/main/java/org/dhis2/data/fingerprint/FingerPrintController.kt
  app/src/main/java/org/dhis2/data/fingerprint/FingerPrintControllerImpl.kt
  app/src/main/java/org/dhis2/data/fingerprint/FingerPrintModule.kt
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/main/res/layout/dialog_body.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1366 fix: [ANDROAPP-2985] Crash when starting app
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/utils/extension/ActivityExtension.kt
Labels: Ready for merge, Tested, bug

#1376 fix: [ANDROAPP-2665] RTL Fix relationship labels in arabic
  customFab/build.gradle
  customFab/src/main/java/com/wangjie/rapidfloatingactionbutton/RapidFloatingActionContent.java
  customFab/src/main/java/com/wangjie/rapidfloatingactionbutton/RapidFloatingActionLayout.java
  customFab/src/main/java/com/wangjie/rapidfloatingactionbutton/contentimpl/labellist/RapidFloatingActionContentLabelList.java
  customFab/src/main/res/layout/rfab__content_label_list_item.xml
  customFab/src/main/res/layout/rfab__content_text.xml
Labels: Tested, bug

#1377 fix: [ANDROAPP-2878] Search form is cleared when rotating
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1382 fix: [ANDROAPP-3021] don't count fields without section for percentage
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1379 fix: [ANDROAPP-2963] Set incident date without hours and minutes
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Tested, bug

#1380 fix: [ANDROAPP-3020] Tint event initial icon with the same colors as in home screen
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/res/layout/activity_event_initial.xml
Labels: Tested, bug

#1383 fix: [ANDROAPP-3023] Filter "Not synced" adding uploading as a different "To post" state
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/test/java/org/dhis2/utils/filters/FilterManagerTest.kt
Labels: Tested, bug

#1385 fix: [ANDROAPP-3022] Fixes bug with back button on enrollment and event forms
  app/src/main/java/org/dhis2/Bindings/Extensions.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1386 fix: [ANDROAPP-2872] Updates viewpager dotsindicator library to work with ViewPager2
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  viewpagerdotsindicator/build.gradle
  viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/DotsIndicator.java
  viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/SpringDotsIndicator.java
  viewpagerdotsindicator/src/main/java/com/tbuonomo/viewpagerdotsindicator/WormDotsIndicator.java
Labels: Ready for merge, bug

#1384 fix: [ANDROAPP-3024] Do not hide filters icon if no data is returned
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1388 fix: ANDROAPP-3032
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
Labels: Ready for merge, Tested, bug

#1392 feat: [ANDROAPP-3010] Overview tab for data sets
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableComponent.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/TableCheckboxAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/TableCheckboxViewHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailComponent.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailPresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailView.kt
  app/src/main/res/drawable/round_squared_bg.xml
  app/src/main/res/drawable/rounded_square_4dp.xml
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/main/res/layout/fragment_dataset_detail.xml
  app/src/main/res/layout/item_table_checkbox.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
Labels: enhancement

#1396 docs: Update documentation with Program Rule differences web/Android [skip ci]
  docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
  docs/src/commonmark/en/resources/images/admin/icon-negative.png
  docs/src/commonmark/en/resources/images/admin/icon-negative.svg
Labels: Documentation

#1402 fix: 2.1.2 androapp 3076
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
Labels: Ready for merge, Tested, bug

#1405 fix: [ANDROAPP-3073] sort order of the options in the OptionSet
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1407 fix: [ANDROAPP-3036] Adds onfocusonchange listener to sync parameters' fields
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
Labels: Ready for merge, Tested, bug

#1415 fix: [ANDROAPP-3037] Update completeness label when updated
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
Labels: Ready for merge, Tested, bug

#1416 docs: Added information about auto-generated expired values [skip ci]
  docs/src/commonmark/en/content/implementation-guide/dhis2-configuration-for-android.md
Labels: Documentation

#1410 fix: [ANDROAPP-3077] Show complete text in dataset column header
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetRHeaderHeader.java
  app/src/main/res/layout/item_dataset_header.xml
Labels: Ready for merge, Tested, bug

#1412 fix: [ANDROAPP-3041] back/close keyboard on the search fields.
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, bug

#1406 feat: Geometry Maps
  app/build.gradle
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/uicomponents/map/MapController.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/GeometryUtils.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/bound/BoundsGeometry.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/MapEventToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/MapGeometryToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/MapTeisToFeatureCollection.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/Mapper.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/mapper/TeisMapperExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/point/MapPointToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonPointToFeature.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonToFeature.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapEventToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapGeometryToFeatureTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/MapTeisToFeatureCollectionTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/bound/BoundGeometryTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/point/MapPointToFeatureTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/point/PointViewModelTest.kt
  app/src/test/java/org/dhis2/uicomponents/map/geometry/polygon/MapPolygonToFeatureTest.kt
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1414 fix: [ANDROAPP-3038] Wrong behaviour when selecting a non visible cell in the table
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
  app/src/main/res/layout/custom_text_view_cell.xml
  tableview/src/main/java/com/evrencoskun/tableview/ITableView.java
  tableview/src/main/java/com/evrencoskun/tableview/TableView.java
  tableview/src/main/java/com/evrencoskun/tableview/handler/ScrollHandler.java
  tableview/src/main/java/com/evrencoskun/tableview/handler/SelectionHandler.java
Labels: Ready for testing, bug

#1417 feat: [ANDROAPP-2991] Map layer manager
  app/src/main/java/org/dhis2/uicomponents/map/MapStyle.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/LayerType.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/HeatmapMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Ready for merge, Tested, enhancement

#1420 feat: [ANDROAPP-1157, ANDROAPP-3000] ValidationRule engine and marked as complete
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryTest.kt
Labels: Tested, enhancement
