Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-01, with the labels that each got.

#1046 docs: Updating screenshots and links
  docs/contribute-to-the-app.md
  docs/features-supported.md
  docs/new-android-specific-features.md
  docs/new-settings.md
  docs/new-visual-configurations.md
  docs/program-rules-supported-in-android-capture-app.md
  docs/programs-specific-features.md
  docs/recommendations-for-a-dhis2-mobile-deployment.md
  docs/resources/images/image15.jpg
  docs/resources/images/image15.png
  docs/resources/images/image17.jpg
  docs/resources/images/image17.png
  docs/resources/images/image19.jpg
  docs/resources/images/image19.png
  docs/resources/images/image2.PNG
  docs/resources/images/image2.jpg
  docs/resources/images/image26.jpg
  docs/resources/images/image26.png
  docs/resources/images/image28.png
  docs/resources/images/image32.jpg
  docs/resources/images/image36.PNG
  docs/resources/images/image36.jpg
  docs/resources/images/image43.jpg
  docs/resources/images/image63.PNG
  docs/resources/images/image63.jpg
  docs/resources/images/image77.jpg
  docs/resources/images/image77.png
  docs/resources/images/image85.jpg
  docs/resources/images/image85.png
Labels: Ready for merge

#1090 test: adds programStageSelectionPresenter test
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionActivity.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionContract.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionModule.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionPresenter.java
  app/src/test/java/org/dhis2/usescases/programstageselection/ProgramStageSelectionPresenterTest.kt
Labels: Ready for merge, Unit Test

#1091 test: adds dataSetInitialPresenter test
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialContract.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialModule.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.java
  app/src/main/res/layout/activity_dataset_initial.xml
  app/src/test/java/org/dhis2/usescases/DataSetInitialPresenterTest.kt
Labels: Ready for merge, Unit Test

#1092 test: adds test on programEventDetailPresenter
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Ready for merge, Unit Test

#1094 fix: coordinates callback
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
Labels: bug

#1112 fix: Program Rule effect showing code or name vale for different events in an enrollment
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
Labels: Tested, bug, waiting for approval

#1117 fix: Online records displaying code instead of name of option
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Tested, bug, waiting for approval

#1093 test: adds test on enrollmentPresenter
  app/build.gradle
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
  app/src/main/java/org/dhis2/usescases/about/AboutContracts.java
  app/src/main/java/org/dhis2/usescases/about/AboutFragment.java
  app/src/main/java/org/dhis2/usescases/about/AboutModule.java
  app/src/main/java/org/dhis2/usescases/about/AboutPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/main/java/org/dhis2/usescases/map/MapSelectorActivity.kt
  app/src/main/java/org/dhis2/usescases/map/multipolygon/MultiPolygonViewModel.kt
  app/src/main/java/org/dhis2/usescases/map/point/PointViewModel.kt
  app/src/main/java/org/dhis2/usescases/map/polygon/PolygonViewModel.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterImpl.java
  app/src/main/java/org/dhis2/utils/DhisTextUtils.kt
  app/src/test/java/org/dhis2/usescases/about/AboutPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
  app/src/test/java/org/dhis2/usescases/map/PointViewModelTest.kt
  app/src/test/java/org/dhis2/usescases/map/PolygonViewModelTest.kt
Labels: Unit Test

#1120 docs: transifex link [skip ci]
  docs/contribute-to-the-app.md
Labels: Documentation

#1118 fix: Double click formulary
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: Ready for merge, Tested, bug

#1119 feat: adds informative messages when sync with SMS
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
Labels: enhancement, waiting for approval

#1121 fix: I set, ask pin everytime the app restarts
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/Bindings/Extensions.kt
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/main/java/org/dhis2/usescases/splash/SplashPresenter.kt
  app/src/main/java/org/dhis2/utils/session/PinDialog.kt
  app/src/main/java/org/dhis2/utils/session/PinExtensions.kt
  app/src/main/java/org/dhis2/utils/session/PinModule.kt
  app/src/main/java/org/dhis2/utils/session/PinPresenter.kt
  app/src/main/java/org/dhis2/utils/session/PinView.kt
  app/src/main/java/org/dhis2/utils/session/SessionComponent.kt
  app/src/main/res/anim/pin_dialog_anim_enter.xml
  app/src/main/res/anim/pin_dialog_anim_exit.xml
  app/src/main/res/layout-land/layout_pin.xml
  app/src/main/res/layout/dialog_pin.xml
  app/src/main/res/layout/layout_pin.xml
  app/src/main/res/menu/main_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
  app/src/test/java/org/dhis2/utils/session/PinPresenterTest.kt
Labels: bug, waiting for approval

#1131 docs: Update dhis2_android_capture_app_INDEX.md [skip ci]
  docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
Labels: Documentation

#1106 test: adds teiDashboardPresenter tests
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenterTest.kt
Labels: Unit Test, waiting for approval

#1132 test: [ANDROAPP-2644] adds test cases on dataSetInitialRepository
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/datasets/dataSetInitial/DataSetInitialRepositoryImplTest.kt
Labels: Ready for merge, Unit Test

#1125 feat(EventCapture): [ANDROAPP-1998] ask user to confirm deletion when going back on newly created event
  app/build.gradle
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/java/org/dhis2/utils/EventMode.kt
Labels: Ready for merge, enhancement

#1134 fix: [ANDROAPP-2650] Check if value is correct before getting/saving it
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/AttributeValueStore.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryStore.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataValueStore.java
  app/src/main/java/org/dhis2/data/forms/dataentry/StoreResult.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStore.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
  app/src/test/java/org/dhis2/usescases/datasets/DataValuePresenterTest.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: bug, waiting for approval

#1138 test(DataSetDeatil): [ANDROAPP-2566] add tests to dataset detail repository
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryTest.kt
Labels: Ready for merge, Unit Test

#1142 fix(ProgramEventDetail): [ANDROAPP-2673] fixes that the sync dialog was not showing.
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
Labels: Ready for merge, bug

#1140 fix: [ANDROAPP-2659] don't search if all fields are empty
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, bug

#1143 fix: [ANDROAPP-1998] don't save event on back
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, bug

#1147 docs: Modify building scripts to match upstream [skip ci]
  docs/build.sh
  docs/build_translations.sh
  docs/lib/doc_functions.sh
  docs/src/commonmark/en/content/capture-app/recommendations-for-a-dhis2-mobile-deployment.md
  docs/src/commonmark/en/content/common/about-this-android-guide.md
  docs/src/commonmark/en/resources/css/dhis2.css
  docs/src/commonmark/en/resources/css/mkdocs_dhis2.css
  docs/src/commonmark/en/resources/images/admin/caution.png
  docs/src/commonmark/en/resources/images/admin/example.png
  docs/src/commonmark/en/resources/images/admin/github.png
  docs/src/commonmark/en/resources/images/admin/icon-complete.png
  docs/src/commonmark/en/resources/images/admin/icon-complete.svg
  docs/src/commonmark/en/resources/images/admin/icon-incomplete.png
  docs/src/commonmark/en/resources/images/admin/icon-incomplete.svg
  docs/src/commonmark/en/resources/images/admin/icon-na.png
  docs/src/commonmark/en/resources/images/admin/icon-na.svg
  docs/src/commonmark/en/resources/images/admin/icon-wip.png
  docs/src/commonmark/en/resources/images/admin/icon-wip.svg
  docs/src/commonmark/en/resources/images/admin/important.png
  docs/src/commonmark/en/resources/images/admin/note.png
  docs/src/commonmark/en/resources/images/admin/tip.png
  docs/src/commonmark/en/resources/images/admin/warning.png
  docs/src/commonmark/en/resources/images/logo.png
  docs/src/commonmark/en/resources/images/logo.svg
Labels: Documentation

#1145 fix: [ANDROAPP-2664] Filter out active events with dates in the future
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/RulesUtilsProvider.kt
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/main/java/org/dhis2/utils/UtilsModule.java
  app/src/main/res/values/strings.xml
  app/src/test/java/android/text/TextUtils.java
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.java
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
Labels: bug, waiting for approval

#1144 feat: [ANDROAPP-817] adds notes tab on event view
  app/src/main/java/org/dhis2/Bindings/StringExtensions.kt
  app/src/main/java/org/dhis2/data/user/UserComponent.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
  app/src/main/java/org/dhis2/usescases/notes/NoteType.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesAdapter.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesComponent.java
  app/src/main/java/org/dhis2/usescases/notes/NotesFragment.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesModule.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesPresenter.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesRepository.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesView.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardComponent.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerTabletAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/notes/NotesViewholder.java
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/layout/fragment_notes.xml
  app/src/main/res/layout/item_note.xml
  app/src/test/java/org/dhis2/bindings/StringExtensionsTest.kt
  app/src/test/java/org/dhis2/usescases/notes/NotesPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/notes/NotesRepositoryTest.kt
Labels: Ready for testing, enhancement

#1151 docs: new icons in features charts [skip ci]
  docs/src/commonmark/en/content/capture-app/features-supported.md
  docs/src/commonmark/en/content/capture-app/program-indicators.md
  docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
  docs/src/commonmark/en/content/capture-app/value-types-supported.md
Labels: Documentation

#1155 docs: transform html tables to GFM [skip ci]
  docs/src/commonmark/en/content/implementation-guide/dhis2-configuration-for-android.md
  docs/src/commonmark/en/content/implementation-guide/testing.md
Labels: Documentation

#1152 fix: [ANDROAPP-2681] attributes on dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
Labels: Ready for merge, bug

#1153 fix: [ANDROAPP-2682] Update coordinates after accepting permissions
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
Labels: Ready for merge, bug

#1148 feat: [ANDROAPP-2670] Add/detail note usecase
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/Bindings/EditTextExtensions.kt
  app/src/main/java/org/dhis2/Bindings/Extensions.kt
  app/src/main/java/org/dhis2/data/user/UserComponent.java
  app/src/main/java/org/dhis2/usescases/notes/NoteItemClickListener.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesAdapter.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesFragment.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesViewHolder.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailActivity.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailComponent.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailModule.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailPresenter.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailRepository.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/notes/noteDetail/NoteDetailView.kt
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/res/layout/activity_note_detail.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/notes/noteDetail/NoteDetailPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/notes/noteDetail/NoteDetailRepositoryTest.kt
Labels: Ready for merge, enhancement

#1156 fix: [ANDROAPP-2680] view and create notes when enrollment is complet…
  app/src/main/java/org/dhis2/usescases/notes/NotesFragment.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesPresenter.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesRepository.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesView.kt
  app/src/main/java/org/dhis2/usescases/notes/NotesViewHolder.kt
  app/src/main/res/drawable/ic_no_notes.xml
  app/src/main/res/layout/fragment_notes.xml
  app/src/main/res/layout/item_notes.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/notes/NotesPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/notes/NotesRepositoryTest.kt
Labels: Ready for merge, bug

#1158 fix: ANDROAPP-1670 Fixed Read barcode / qr Code in Form Enrollment
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: Ready for merge, Tested, bug

#1139 fix: [ANDROAPP-2650] Fixed remaining value checks that blocked data entry
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
Labels: Ready for testing, bug

#1162 refactor: [ANDROAPP-1273] Add userId to analytics
  app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
Labels: Ready for merge
