Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-09, with the labels that each got.

#1606 fix: [ANDROAPP-3307] Search's clear button is now working
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, bug

#1604 fix: [ANDROAPP-3309] Shows Dataset save button after Validations error dialog is displayed and closed
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
Labels: Ready for merge, Tested, bug

#1603 fix: [ANDROAPP-3296] Fixed org. unit list crash when scrolling
  app/src/main/java/org/dhis2/usescases/orgunitselector/OUTreeActivity.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorAdapter.java
  app/src/main/java/org/dhis2/usescases/orgunitselector/OrgUnitSelectorHolder.kt
  app/src/main/java/org/dhis2/usescases/orgunitselector/TreeNodeCallback.kt
Labels: Ready for merge, Tested, bug

#1605 fix: [ANDROAPP-3308] Fix crash when using event date sorting
  app/src/main/java/org/dhis2/data/sorting/SearchSortingValueSetter.kt
  app/src/test/java/org/dhis2/data/sorting/SearchSortingValueSetterTest.kt
Labels: Ready for merge, Tested, bug

#1607 fix: [ANDROAPP-3306] check section is not hidden on percentage calcul…
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/GetNextVisibleSection.kt
Labels: Ready for merge, Tested, bug

#1602 fix: [ANDROAPP-3294] display TEI images on map
  app/src/main/java/org/dhis2/uicomponents/map/TeiMarkers.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/res/drawable/bg_image_marker.xml
Labels: Ready for merge, Tested

#1599 fix: [ANDROAPP-3293] Greyed fields are not being respected
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenterTest.kt
Labels: Ready for merge, Tested, bug

#1609 fix: [ANDROAPP-3298] Rotates captured photo if need, correctly
  app/build.gradle
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/utils/ImageUtils.kt
Labels: Ready for merge, Tested, bug

#1608 fix: [ANDROAPP-2766] New event card design
  app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/EventWithoutRegistrationRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/robot/SyncFlowRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailAdapter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailLiveAdapter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewHolder.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewModel.kt
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/item_event.xml
  app/src/main/res/layout/item_program_event.xml
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Tested, design, enhancement

#1597 fix: [ANDROAPP-3282] map issues
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/mapper/EventToEventUiComponent.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/CarouselItemModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/EventUiComponentModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/RelationshipUiComponentModel.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventViewModel.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
Labels: Ready for merge, Tested, bug

#1611 feat: [ANDROAPP-3006] changes the design of image fields in the forms.
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureHolder.java
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
  app/src/main/res/layout/form_picture.xml
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, design

#1613 fix: [ANDROAPP-3247] Do not auto-remove value from local database after showError action
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1614 fix: [ANDROAPP-2917] field titles redesign
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/res/drawable-v19/item_selected_bg.xml
  app/src/main/res/drawable/item_selected_bg.xml
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/custom_text_view_accent.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Ready for merge, Tested, design

#1612 feat: [ANDROAPP-2778] Use displayDescription instead of conflict
  app/src/main/java/org/dhis2/data/service/SyncGranularRxWorker.java
  app/src/main/java/org/dhis2/data/service/SyncPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/settings/models/ErrorModelMapper.kt
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/test/java/org/dhis2/usescases/settings/models/ErrorModelMapperTest.kt
Labels: Ready for merge, Tested, enhancement

#1619 feat: [ANDROAPP-3007, ANDROAPP-3008] longtext, date, datetime, time and age fields redesign
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/utils/customviews/AgeView.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
  app/src/main/res/layout/age_custom_view.xml
  app/src/main/res/layout/age_custom_view_accent.xml
  app/src/main/res/layout/custom_long_text_view.xml
  app/src/main/res/layout/custom_long_text_view_accent.xml
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/custom_text_view_accent.xml
  app/src/main/res/layout/date_time_view.xml
  app/src/main/res/layout/date_time_view_accent.xml
  app/src/main/res/layout/time_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: Ready for merge, Tested, design

#1622 refactor: [ANDROAPP-2868] Increase timeout connection to 10 minutes
  app/src/androidTest/java/org/dhis2/usescases/settings/SettingsTest.kt
  app/src/main/java/org/dhis2/data/server/ServerModule.java
Labels: enhancement

#1617 feat: [ANDROAPP-3026] Show progress while loading form
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormPresenter.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/layout/enrollment_activity.xml
Labels: Ready for merge, Tested, enhancement

#1621 feat: [ANDROAPP-3272] Check TrackerImportConflict to validate attributes and/or data elements
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, Tested, enhancement

#1625 fix: [ANDROAPP-3315] change info icon for clear button in server url
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
Labels: Ready for merge, Tested, design

#1627 feat: [ANDROAPP-2998] checks for debugger in release apk
  app/src/main/java/org/dhis2/usescases/splash/SplashActivity.kt
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, enhancement

#1626 fix: [ANDROAPP-3319] Ask user to create new event when stage is compl…
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
Labels: Ready for merge, Tested, bug

#1630 feat: Enable acra
  app/src/main/java/org/dhis2/App.java
Labels: Ready for merge, Tested

#1631 fix: [ANDROAPP-3330] Prevents crash when section has no data elements
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
Labels: Ready for merge, Tested, bug

#1632 fix: Navigate back to home from a different section in navigation drawer
  app/src/androidTest/java/org/dhis2/usescases/main/MainRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/main/MainTest.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/main/java/org/dhis2/usescases/main/MainView.kt
  app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1638 chore: [ANDROAPP-3347] updates the custom crash activity's strings
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1635 fix: [ANDROAPP-3326] Prevent crash on datasets with optionset
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
Labels: Ready for merge, Tested, bug

#1636 fix: [ANDROAPP-3342] Do not round value in field of ValueType UNIT_INTERVAL
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/test/java/org/dhis2/bindings/ValueExtensionsTest.kt
Labels: Ready for merge, Tested, bug

#1637 fix: [ANDROAPP-3338] Removes top padding and adds bottom padding to fields layout
  app/src/main/assets/paperwork.json
  app/src/main/res/layout/age_custom_view.xml
  app/src/main/res/layout/age_custom_view_accent.xml
  app/src/main/res/layout/custom_long_text_view.xml
  app/src/main/res/layout/custom_long_text_view_accent.xml
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/custom_text_view_accent.xml
  app/src/main/res/layout/date_time_view.xml
  app/src/main/res/layout/date_time_view_accent.xml
  app/src/main/res/layout/form_coordinates.xml
  app/src/main/res/layout/form_coordinates_accent.xml
  app/src/main/res/layout/form_spinner.xml
  app/src/main/res/layout/form_spinner_accent.xml
  app/src/main/res/layout/scan_text_view.xml
  app/src/main/res/layout/scan_text_view_accent.xml
  app/src/main/res/layout/yes_no_view.xml
  app/src/main/res/layout/yes_no_view_primary.xml
Labels: Ready for merge, Tested, bug

#1639 fix: [ANDROAPP-3348] Disable edition of fields when value is assigned
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/file/FileViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/unsupported/UnsupportedViewModel.java
Labels: Ready for merge, Tested, bug

#1640 fix: [ANDROAPP-3346] Apply displayInList in dashboard TEI card
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
Labels: Ready for merge, Tested, bug

#1633 fix: [ANDROAPP-3333] form design improvements
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitHolder.java
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
  app/src/main/java/org/dhis2/utils/customviews/AgeView.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
  app/src/main/java/org/dhis2/utils/customviews/OrgUnitView.java
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
  app/src/main/res/layout/custom_long_text_view.xml
  app/src/main/res/layout/custom_long_text_view_accent.xml
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/form_coordinates.xml
  app/src/main/res/layout/form_coordinates_accent.xml
  app/src/main/res/layout/form_picture.xml
  app/src/main/res/layout/form_picture_accent.xml
  app/src/main/res/layout/yes_no_view.xml
  app/src/main/res/layout/yes_no_view_primary.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: Ready for merge, Tested, bug

#1641 fix: [Androapp 3255] Change downloading feedback
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: Ready for merge, Tested, bug

#1643 fix: selected image overlap current and is not displayed behind
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
Labels: Ready for merge, Tested, bug

#1644 fix: [ANDROAPP-3349] crash when reset search with all TET
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, bug

#1646 fix: [ANDROAPP-3352] Warning showing for unique value
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
Labels: Ready for merge, Tested, bug

#1645 fix: [ANDROAPP-3341] Tracker conflict in event prevent showing form
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1629 fix: [ANDROAPP-2815] add allowOnlineCache when search parameters are …
  app/src/main/java/org/dhis2/data/search/SearchParametersModel.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/filters/EnrollmentDateFilterHolder.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
Labels: Ready for merge, Tested, bug

#1647 fix: [ANDROAPP-3351] Do not show warning/error badge in section until save button is pressed
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for merge, Tested, bug

#1634 fix: [ANDROAPP-3329] Event item layout design fixes
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewModel.kt
  app/src/main/res/layout/item_event.xml
  app/src/main/res/layout/item_stage_section.xml
Labels: Ready for merge, Tested, bug, design

#1642 fix: ANDROAPP-3323 Search network calls
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTeiRobot.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/filters/EnrollmentDateFilterHolder.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Tested, bug

#1651 fix: [ANDROAPP-3345] Display view model method setting null in nonnull variable
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
Labels: Ready for merge, Tested, bug

#1652 fix: [ANDROAPP-3355] DataSet share settings are not applying properly
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/coordinate/CoordinateViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/datetime/DateTimeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/file/FileViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/image/ImageViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/orgUnit/OrgUnitViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/spinner/SpinnerViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/unsupported/UnsupportedViewModel.java
Labels: Ready for merge, Tested, bug

#1653 fix: [ANDROAPP-3358] crash when changing program from all TET
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, bug

#1650 fix: [ANDROAPP-3343] check if coming from camera or gallery before re…
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
Labels: Ready for merge, Tested, bug

#1654 fix: [ANDROAPP-3353] Avoids showing a floating header on an form without section
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: Ready for merge, Tested, bug

#1655 fix: [ANDROAPP-3363] Relationship Tei cards List not showing attributes in same order
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/RelationshipLiveAdapter.java
Labels: Ready for merge, Tested, bug

#1658 fix: [ANDROAPP-3357] Allow new enrollment when minAttributesToSearch is 0
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for merge, Tested, bug

#1656 fix: [ANDROAPP-3362] image issues
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
Labels: Ready for merge, Tested, bug

#1662 fix: [ANDROAPP-3369] Do not copy FilterManager values using equal assignments
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
Labels: Ready for merge, Tested, bug

#1663 refactor: Kotlin in about screen
  app/src/androidTest/java/org/dhis2/usescases/about/AboutTest.kt
  app/src/main/java/org/dhis2/usescases/about/AboutComponent.java
  app/src/main/java/org/dhis2/usescases/about/AboutComponent.kt
  app/src/main/java/org/dhis2/usescases/about/AboutContracts.java
  app/src/main/java/org/dhis2/usescases/about/AboutFragment.java
  app/src/main/java/org/dhis2/usescases/about/AboutFragment.kt
  app/src/main/java/org/dhis2/usescases/about/AboutModule.java
  app/src/main/java/org/dhis2/usescases/about/AboutModule.kt
  app/src/main/java/org/dhis2/usescases/about/AboutPresenter.kt
  app/src/main/java/org/dhis2/usescases/about/AboutPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/about/AboutView.kt
  app/src/main/res/layout/fragment_about.xml
  app/src/test/java/org/dhis2/usescases/about/AboutPresenterTest.kt
Labels: refactor

#1657 test: [ANDROAPP-3321] Flow ui test
  app/src/androidTest/java/org/dhis2/AppTest.kt
  app/src/androidTest/java/org/dhis2/usescases/flow/syncFlow/SyncFlowTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/java/org/dhis2/data/service/SyncGranularWorker.kt
Labels: espresso test

#1659 fix: [ANDROAPP-3364] User friendly value not shown in event cards
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
Labels: Ready for merge, Tested, bug

#1665 fix: [ANDROAPP-3373] Date fields not removing focus from text fields
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
  app/src/main/java/org/dhis2/utils/customviews/TimeView.java
Labels: Ready for merge, bug

#1667 fix: [ANDROAPP-3378] Option sets in data set had white text color
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
Labels: Ready for testing, bug

#1670 fix: [ANDROAPP-3379] Revert to value path for images
  app/src/main/java/org/dhis2/Bindings/ValueExtensions.kt
Labels: Ready for merge, Tested, bug

#1675 fix: [ANDROAPP-3336] set button not enabled when not field is not editable
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
Labels: Ready for merge, Tested, bug

#1678 fix: Adds validation to check if the PR already has an approval, comment or a change requested
  scripts/reviewers.py
Labels: Ready for merge, enhancement

#1680 fix: [ANDROAPP-3397] Check was hiding main attribute in carousel item
  app/src/main/res/layout/item_carousel_tei.xml
Labels: Ready for merge, bug

#1672 fix: ANDROAPP-3332 Update map when event changes coordinates
  app/src/main/java/org/dhis2/data/prefs/Preference.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1677 fix: [ANDROAPP-3186] Show description icon when test is ellipsized
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
  app/src/main/res/layout/form_section.xml
  app/src/test/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModelTest.kt
Labels: Ready for merge, Tested, bug

#1669 fix: [ANDROAPP-3373] Missing date and dateTime formats
  app/src/main/java/org/dhis2/utils/customviews/DateTimeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateView.java
Labels: Ready for merge, Tested, bug
