Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-07, with the labels that each got.

#1474 fix: Crash in searchTei due to null value in teicard
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
Labels: Ready for merge, Tested, bug

#1476 fix: Rollback section scrolling
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
Labels: Ready for merge, Tested

#1472 feat: [ANDROAPP-2295] Add search option for category option and category option combo selectors
  app/src/main/java/org/dhis2/data/server/ServerComponent.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailView.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialContract.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepository.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepository.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/utils/category/CategoryDialog.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogAdapter.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogComponent.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogHolder.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogItem.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogModule.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogPresenter.kt
  app/src/main/java/org/dhis2/utils/category/CategoryDialogView.kt
  app/src/main/java/org/dhis2/utils/category/CategoryOptionCategoryDialogItemMapper.kt
  app/src/main/java/org/dhis2/utils/category/CategoryOptionComboCategoryDialogItemMapper.kt
  app/src/main/java/org/dhis2/utils/filters/CatOptCombFilterHolder.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/res/layout/filter_cat_opt_comb.xml
  app/src/test/java/org/dhis2/utils/category/CategoryDialogPresenterTest.kt
  app/src/test/java/org/dhis2/utils/category/CategoryOptionCategoryDialogItemMapperTest.kt
  app/src/test/java/org/dhis2/utils/category/CategoryOptionComboCategoryDialogItemMapperTest.kt
Labels: Ready for merge, Tested, enhancement

#1467 feat: [ANDROAPP-3114] Inherit values
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
Labels: Ready for testing, enhancement

#1477 fix: [ANDROAPP-3143] Set viewpager2 in event data entry
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
  app/src/main/res/layout/activity_event_capture.xml
Labels: bug, waiting for approval

#1478 fix: [ANDROAPP-3113] close keyboard before open calendar picker
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
Labels: Ready for testing, bug

#1479 fix: [ANDROAPP-3161] Map view not updated when filters are used
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/SatelliteMapLayer.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1481 fix: [ANDROAPP-3098] add horizontal scroll when to many options
  app/src/main/res/layout/form_spinner_selection.xml
Labels: Ready for merge, Tested, bug

#1484 fix: [ANDROAPP-3166] Fixes crash when selectedEnrollment is null in SearchTEViewHolder
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
Labels: Ready for merge, Tested, bug

#1485 fix: [ANDROAPP-3164] avoid showing orgUnit dialog two times
  app/src/main/java/org/dhis2/usescases/datasets/datasetInitial/DataSetInitialActivity.java
Labels: Ready for merge, Tested, bug

#1486 fix: [ANDROAPP-3158] disable horizontal swipe on dataset tabs
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
Labels: Ready for merge, Tested, bug

#1491 fix: [ANDROAPP-3173] fix the assigned to me filter switch
  app/src/main/java/org/dhis2/utils/filters/AssignToMeFilterHolder.kt
Labels: Ready for testing, bug

#1488 fix: [ANDROAPP-3169] check presenter is initialized
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
Labels: Ready for merge, bug

#1494 feat: [ANDROAPP-3172] add carousel to program events map
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventViewModel.java
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/item_carousel_program_event.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Tested, enhancement, on pause

#1482 fix: [ANDROAPP-3155] TEI card design fixes
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/Bindings/DateExtensions.kt
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/data/enrollment/EnrollmentUiDataHelper.kt
  app/src/main/java/org/dhis2/data/sorting/SearchSortingValueSetter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/main/java/org/dhis2/utils/filters/EnrollmentDateFilterHolder.java
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
  app/src/main/res/anim/fragment_enter_left.xml
  app/src/main/res/anim/fragment_enter_right.xml
  app/src/main/res/anim/fragment_exit_left.xml
  app/src/main/res/anim/fragment_exit_right.xml
  app/src/main/res/layout/item_carousel_event.xml
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/dhis2/data/sorting/SearchSortingValueSetterTest.kt
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Tested, bug, design

#1496 fix: [ANDROAPP-3162] refreshes events status when enrollment is completed/reopen
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
Labels: Tested, bug

#1489 fix: Limits location values to no more than 5 decimal
  app/src/main/java/org/dhis2/Bindings/DoubleExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/MapSelectorActivity.kt
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
Labels: Tested, bug

#1498 fix: [ANDROAPP-3168] handle tei last update date on server after devi…
  app/src/main/java/org/dhis2/Bindings/DateExtensions.kt
  app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt
Labels: Ready for merge, Tested, bug

#1497 fix: [ANDROAPP-3014] display fields do not count for percentage
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1503 fix: [ANDROAPP-3182] save server and user when login
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
Labels: Ready for testing, bug

#1504 fix: [ANDROAPP-3176] Overdue icon does not render correctly in filters
  app/src/main/res/drawable/ic_overdue_filter.xml
  app/src/main/res/layout/filter_status.xml
Labels: Tested, bug

#1502 chore: [ANDROAPP-3174] Changes Events fragments title
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: Tested, enhancement

#1495 fix: Androapp 3171 Parent Database adapter crash
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/widgets/DhisCustomLauncher.kt
Labels: Tested, bug

#1511 feat: [ANDROAPP-3190] Maps improvements
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselRelationshipHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/RelationshipMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/model/TeiRelationShipsMapModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventMapper.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventViewModel.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/res/drawable/avatar_main_defalut_bg.xml
  app/src/main/res/drawable/avatar_sec_defalut_bg.xml
  app/src/main/res/layout/item_carousel_event.xml
  app/src/main/res/layout/item_carousel_program_event.xml
  app/src/main/res/layout/item_carousel_relationship.xml
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_no_coordinates.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Ready for testing

#1470 feat: Matomo and Acra - Androapp 3124
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/data/server/ServerModule.java
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/utils/analytics/AnalyticsHelper.kt
  app/src/main/java/org/dhis2/utils/analytics/AnalyticsInterceptor.kt
  app/src/main/java/org/dhis2/utils/analytics/AnalyticsModule.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsController.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsControllerImpl.kt
  app/src/main/java/org/dhis2/utils/analytics/matomo/MatomoAnalyticsModule.kt
  app/src/main/res/values/styles.xml
Labels: Ready for testing

#1512 fix: [ANDROAPP-3174] change string resource Details to Data
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
Labels: bug, waiting for approval

#1517 fix: [ANDROAPP-3162] Changes event status when enrollment is completed/re-open/deactivate
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/EventViewHolder.java
Labels: Ready for merge, Tested, bug

#1516 fix: [ANDROAPP-3078] Numeric value type formats
  app/src/main/java/org/dhis2/utils/ValidationUtils.kt
  app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
Labels: Ready for merge, Tested, bug

#1515 fix: [ANDROAPP-3197] Data set layout errors
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/res/layout/fragment_validation_result_violation.xml
Labels: Ready for testing, bug

#1514 fix: [ANDROAPP-3195] Remove request focus when field has error
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: Ready for testing, bug

#1523 fix: [ANDROAPP-2911] Removes pin windows when a user logout
  app/src/main/java/org/dhis2/usescases/main/MainPresenter.kt
  app/src/test/java/org/dhis2/usescases/main/MainPresenterTest.kt
Labels: Ready for merge, Tested, bug

#1522 fix: [ANDROAPP-3207] Fix crash when selecting profile image in dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
Labels: Ready for merge, Tested, bug

#1520 fix: [ANDROAPP-3203] Improved scroll animation for carousel view
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
Labels: Ready for merge, Tested, enhancement

#1524 fix: [ANDROAPP-3205] Improvements in Event Maps
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/TeiEventMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/EventMapManager.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
Labels: Ready for merge, Tested, bug

#1525 fix: [ANDROAPP-3213] Changes dataset details tab title to data
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1490 docs: android settings app webapp documentation [skip ci]
  docs/src/commonmark/en/content/capture-app/app-android-settings-configuration.md
  docs/src/commonmark/en/content/capture-app/resources/images/dataset-global-settings.png
  docs/src/commonmark/en/content/capture-app/resources/images/dataset-specific-dialog.png
  docs/src/commonmark/en/content/capture-app/resources/images/dataset-specific-table.png
  docs/src/commonmark/en/content/capture-app/resources/images/first-setup-no-authorities.png
  docs/src/commonmark/en/content/capture-app/resources/images/first-time-setup.png
  docs/src/commonmark/en/content/capture-app/resources/images/general-settings.png
  docs/src/commonmark/en/content/capture-app/resources/images/install-app.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-global-settings.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-specific-dialog-with_registration.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-specific-dialog-without_registration.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-specific-table.png
  docs/src/commonmark/en/content/capture-app/resources/images/reset-default.png
  docs/src/commonmark/en/content/capture-app/resources/images/save_button.png
  docs/src/commonmark/en/content/capture-app/resources/images/unsaved-changes.png
  docs/src/commonmark/en/content/capture-app/resources/images/user-sync-test.png
  docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
Labels: Documentation, waiting for approval

#1526 fix: [ANDROAPP-3211] Sync icon is not shown when granular sync ends
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetDetail/DataSetDetailFragment.kt
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
Labels: Ready for merge, Tested, bug

#1527 fix: [ANDROAPP-3211] New period labels and enrollment date position
  app/src/main/java/org/dhis2/utils/filters/FiltersAdapter.java
  app/src/main/java/org/dhis2/utils/filters/PeriodFilterHolder.java
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1513 fix: [ANDROAPP-3194] Schedule event can't be posponed or opened
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/TeiDashboardRobot.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/events/ScheduledEventActivity.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
  app/src/main/res/menu/dashboard_menu.xml
  app/src/main/res/menu/dashboard_menu_group.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenterTest.kt
Labels: Ready for merge, bug

#1530 feat: [ANDROAPP-3204] Add loading animations for maps
  app/src/main/java/org/dhis2/animations/CarouselViewAnimations.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselLayoutManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipModule.java
  app/src/main/res/layout-land/activity_dashboard_mobile.xml
Labels: Ready for merge, Tested, enhancement

#1531 fix: [ANDROAPP-3209] Relationship and search list display message when teiType has no attributes to show.
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/RelationshipLiveAdapter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchRelationshipViewHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTEViewHolder.kt
  app/src/main/res/layout/item_search_relationship_tracked_entity.xml
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1532 fix: [ANDROAPP-3216] Fix crashes and rounded corners
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
  app/src/main/java/org/dhis2/utils/customviews/AlertBottomDialog.kt
  app/src/main/res/drawable/ic_bottom_sheet_dialog.xml
  app/src/main/res/layout-land/fragment_program.xml
  app/src/main/res/layout/alert_bottom_dialog.xml
Labels: Ready for merge, Tested, bug

#1534 docs: Fix comment about disabled account [skip ci]
  docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
  docs/src/commonmark/en/content/implementation-guide/SMS-Sync.md
  docs/src/commonmark/en/content/implementation-guide/SMS-for-reporting.md
  docs/src/commonmark/en/content/implementation-guide/installing-the-app.md
  docs/src/commonmark/en/content/implementation-guide/resources/images/android-sms-settings.png
  docs/src/commonmark/en/content/implementation-guide/resources/images/compressed-sms.png
Labels: Documentation

#1510 fix: [ANDROAPP-3159] Online search fixes
  app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/bindings/TrackedEntityInstanceExtensions.kt
Labels: Ready for merge, Tested, bug

#1535 fix: [ANDROAPP-3139] DataSet data entry errors
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
  app/src/main/res/layout/fragment_dataset_section.xml
Labels: Ready for merge, bug

#1533 fix: [ANDROAPP-3215] labels and loading improvements
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/granularsync/SyncStatusDialog.kt
  app/src/main/res/layout-land/activity_event_initial.xml
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/layout/activity_event_initial.xml
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/values/strings.xml
Labels: Ready for merge, bug

#1538 fix: [ANDROAPP-3220] Show only display in list attributes
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1540 fix: [ANDROAPP-3213] Changes the tab title when the dataset has no section from "Tables" to "Data"
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
Labels: Ready for merge, Tested, bug

#1542 fix: [ANDROAPP-3227] Backdrop animation fix
  app/src/dhis/java/org/dhis2/usescases/main/program/ProgramAnimation.kt
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
Labels: Ready for merge, Tested, bug

#1536 fix: [ANDROAPP-3217,3218,3219,3221] ProgramRules fixes
  app/src/androidTest/java/org/dhis2/AppTest.kt
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/AppComponent.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeHolder.java
  app/src/main/java/org/dhis2/data/server/ServerModule.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/main/java/org/dhis2/utils/UtilsModule.java
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
Labels: Ready for merge, Tested, bug

#1545 docs: change installation mode to app store [skip ci]
  docs/src/commonmark/en/content/capture-app/app-android-settings-configuration.md
  docs/src/commonmark/en/content/capture-app/resources/images/app-store-install.png
Labels: Documentation

#1546 fix: update alert dialog with new text and remove negative btn
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/res/layout/filter_enrollment_status.xml
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested

#1537 fix: [ANDROAPP-3167] truncates coordinates values when entered manually by user.
  app/src/main/java/org/dhis2/Bindings/StringExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/LngLatValidator.kt
  app/src/main/java/org/dhis2/usescases/coodinates/CoordinatesView.java
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/bindings/StringExtensionsTest.kt
Labels: Ready for merge, bug

#1543 fix: [ANDROAPP-3226] Filters allow unwanted event creation
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/data/dhislogic/DhisEventUtils.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TeiDataRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/teievents/StageViewHolder.kt
  app/src/main/res/values/strings.xml
Labels: Ready for testing, bug

#1541 fix: [ANDROAPP-3159] Break the glass message
  app/src/main/java/org/dhis2/data/dhislogic/DhisEnrollmentUtils.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListContract.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListInteractor.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenter.java
  app/src/main/res/menu/dashboard_tei_menu.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/data/dhislogic/DhisEnrollmentUtilsTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListPresenterTest.kt
  buildsystem/dependencies.gradle
Labels: Ready for merge, Tested, bug

#1547 fix: [ANDROAPP-3230] Camera moving to places with no coordinates
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerDialog.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/MapLayerManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/EnrollmentMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/layer/types/RelationshipMapLayer.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Ready for merge, Tested, bug

#1549 fix: [ANDROAPP-3245] hide error bottom sheet when clicking save on dataset
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/res/layout/violation_rules_bottom_sheet.xml
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
Labels: Ready for merge, Tested, bug

#1539 fix: [ANDROAPP-3222] Keyboard is closed when moving to next cell
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/edittext/EditTextCellCustomHolder.java
Labels: Tested, bug

#1544 fix: [ANDROAPP-3140] don't lose focus when change focus manually
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FormViewHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
Labels: Ready for testing, Tested, bug

#1552 fix: [ANDROAPP-3228] sets same style to OK button in the dialog
  app/src/main/res/layout/dialog_body.xml
Labels: Ready for merge, Tested, bug

#1550 fix: [ANDROAPP-3244] Event capture with QR
  app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
Labels: Ready for merge, Tested, bug

#1551 fix: [ANDROAPP-3223] check all fields for dataElement required
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableRepositoryImpl.kt
Labels: Ready for merge, Tested, bug

#1556 fix: [ANDROAPP-3246] Fix AgeHolder date format
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/age/AgeHolder.java
  app/src/main/java/org/dhis2/utils/customviews/AgeView.java
  app/src/main/java/org/dhis2/utils/customviews/DateTableView.java
Labels: Tested, bug

#1555 docs: Update 2.2- screenshots, features tables, program rules tables, indicators tables. [skip ci]
  docs/src/commonmark/en/content/capture-app/features-supported.md
  docs/src/commonmark/en/content/capture-app/new-android-specific-features.md
  docs/src/commonmark/en/content/capture-app/new-visual-configurations.md
  docs/src/commonmark/en/content/capture-app/program-indicators.md
  docs/src/commonmark/en/content/capture-app/program-rules-supported-in-android-capture-app.md
  docs/src/commonmark/en/content/capture-app/programs-specific-features.md
  docs/src/commonmark/en/content/capture-app/resources/images/image101.png
  docs/src/commonmark/en/content/capture-app/resources/images/image102.png
  docs/src/commonmark/en/content/capture-app/resources/images/image103.png
  docs/src/commonmark/en/content/capture-app/resources/images/image106.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image106.png
  docs/src/commonmark/en/content/capture-app/resources/images/image113.png
  docs/src/commonmark/en/content/capture-app/resources/images/image114.png
  docs/src/commonmark/en/content/capture-app/resources/images/image115.png
  docs/src/commonmark/en/content/capture-app/resources/images/image116.png
  docs/src/commonmark/en/content/capture-app/resources/images/image117.png
  docs/src/commonmark/en/content/capture-app/resources/images/image118.png
  docs/src/commonmark/en/content/capture-app/resources/images/image122.png
  docs/src/commonmark/en/content/capture-app/resources/images/image123.png
  docs/src/commonmark/en/content/capture-app/resources/images/image124.png
  docs/src/commonmark/en/content/capture-app/resources/images/image125.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image125.png
  docs/src/commonmark/en/content/capture-app/resources/images/image126.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image127.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image127.png
  docs/src/commonmark/en/content/capture-app/resources/images/image128.png
  docs/src/commonmark/en/content/capture-app/resources/images/image129.png
  docs/src/commonmark/en/content/capture-app/resources/images/image130.png
  docs/src/commonmark/en/content/capture-app/resources/images/image131.png
  docs/src/commonmark/en/content/capture-app/resources/images/image132.png
  docs/src/commonmark/en/content/capture-app/resources/images/image133.png
  docs/src/commonmark/en/content/capture-app/resources/images/image134.png
  docs/src/commonmark/en/content/capture-app/resources/images/image135.png
  docs/src/commonmark/en/content/capture-app/resources/images/image136.png
  docs/src/commonmark/en/content/capture-app/resources/images/image137.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image19.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image19.png
  docs/src/commonmark/en/content/capture-app/resources/images/image22.png
  docs/src/commonmark/en/content/capture-app/resources/images/image26.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image26.png
  docs/src/commonmark/en/content/capture-app/resources/images/image30.png
  docs/src/commonmark/en/content/capture-app/resources/images/image36.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image36.png
  docs/src/commonmark/en/content/capture-app/resources/images/image38.png
  docs/src/commonmark/en/content/capture-app/resources/images/image43.png
  docs/src/commonmark/en/content/capture-app/resources/images/image44.png
  docs/src/commonmark/en/content/capture-app/resources/images/image66.png
  docs/src/commonmark/en/content/capture-app/resources/images/image67.png
  docs/src/commonmark/en/content/capture-app/resources/images/image69.png
  docs/src/commonmark/en/content/capture-app/resources/images/image70.png
  docs/src/commonmark/en/content/capture-app/resources/images/image73.png
  docs/src/commonmark/en/content/capture-app/resources/images/image74.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image74.png
  docs/src/commonmark/en/content/capture-app/resources/images/image87.png
  docs/src/commonmark/en/content/capture-app/resources/images/image89.png
  docs/src/commonmark/en/content/capture-app/resources/images/image92.png
  docs/src/commonmark/en/content/capture-app/resources/images/image93.png
  docs/src/commonmark/en/content/capture-app/resources/images/image97.jpg
  docs/src/commonmark/en/content/capture-app/resources/images/image97.png
  docs/src/commonmark/en/dhis2_android_capture_app_INDEX.md
Labels: Documentation
