Repository dhis2/dhis2-android-capture-app, pull requests merged in 2020-03, with the labels that each got.

#1196 feat: [ANDROAPP-656] Support enrollment sections
  app/src/main/java/org/dhis2/Bindings/StringExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryRepository.java
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.java
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/RowAction.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentFormRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/recyclers/StickyHeaderItemDecoration.kt
  app/src/main/res/layout/enrollment_activity.xml
  app/src/main/res/layout/tei_data_header.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for merge, bug

#1206 fix: [ANDROAPP-2782] OptionCode not been selected for program rule variable value
  app/build.gradle
  app/src/main/java/org/dhis2/Bindings/ContextExtensions.kt
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: Ready for testing, bug

#1211 fix: TEI and Enrollment deletion
  app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListAdapter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
Labels: Ready for merge

#1207 feat: Show build info in login screen
  app/build.gradle
  app/src/main/java/org/dhis2/Bindings/ContextExtensions.kt
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/res/layout-land/activity_login.xml
  app/src/main/res/layout/activity_login.xml
Labels: enhancement, waiting for approval

#1209 fix: [ANDROAPP-2770] Disable settings parameter when there is no internet connection
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
Labels: Ready for merge, Tested, bug

#1212 fix: [ANDROAPP-2767] get next periods of some periodTypes
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/test/java/org/dhis2/utils/DateUtilsTest.java
Labels: Ready for testing, bug

#1208 fix: [ANDROAPP-2773] Fix unique attribute warning
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: Ready for merge, bug

#1210 fix: [ANDROAPP-2768] Hide filters in search screen until a list result is fetch
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_search.xml
Labels: Ready for merge, Tested, bug

#1218 fix: [ANDROAPP-2786] Program rules are not filtered by program stage
  app/src/main/java/org/dhis2/data/forms/EnrollmentFormRepository.java
  app/src/main/java/org/dhis2/data/forms/EventRepository.java
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programStageSelection/ProgramStageSelectionRepositoryImpl.java
  app/src/main/res/values/strings.xml
Labels: Tested, bug

#1219 fix: [ANDROAPP-2757] add sticky header on events
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormFragment.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormPresenter.kt
  app/src/main/java/org/dhis2/utils/recyclers/StickyHeaderItemDecoration.kt
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
  app/src/test/java/org/dhis2/usescases/eventWithoutRegistration/eventCapture/EventCaptureFragment/EventCaptureFormPresenterTest.kt
Labels: Ready for testing, bug

#1226 fix: [ANDROAPP-2729] Location using map in search fields
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Ready for merge, bug

#1231 fix: 2804 mapbox issue
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/main/java/org/dhis2/utils/maps/GeometryUtils.kt
  app/src/main/java/org/dhis2/utils/maps/MapboxExtension.kt
Labels: Tested, bug

#1233 fix: [ANDROAPP-2787] options on tei enrollments
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/res/menu/dashboard_tei_menu.xml
Labels: Ready for testing, bug

#1230 fix: [ANDROAPP-1670] scan only options of optionSet
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
  app/src/main/java/org/dhis2/data/user/UserComponent.java
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/qrScanner/QRActivity.java
  app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
  app/src/main/java/org/dhis2/usescases/qrScanner/ScanComponent.kt
  app/src/main/java/org/dhis2/usescases/qrScanner/ScanModule.kt
  app/src/main/java/org/dhis2/usescases/qrScanner/ScanRepository.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/FormAdapter.java
  app/src/main/java/org/dhis2/utils/Constants.java
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/res/layout/activity_scan.xml
Labels: Ready for merge, Tested, bug

#1234 fix: [ANDROAPP-2805] crash with periodType
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
Labels: Ready for merge, Tested, bug

#1222 fix: [ANDROAPP-2788 | ANDROAPP-2742] Attribute value for rule variable is always empty
  app/src/main/java/org/dhis2/data/forms/RulesRepository.kt
Labels: Tested, bug

#1235 fix: [ANDROAPP-2799] Adds complete/deactivated option to tei dashboard menu
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenter.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
  app/src/main/res/drawable/ic_cancel_menu.xml
  app/src/main/res/drawable/ic_lock_menu.xml
  app/src/main/res/drawable/ic_lock_open_menu.xml
  app/src/main/res/menu/dashboard_menu.xml
  app/src/main/res/menu/dashboard_menu_group.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImplTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/TeiDashboardPresenterTest.kt
Labels: Tested, bug

#1237 fix: [ANDROAPP-2800] Use code for variable not wornking with tracked entity attributes
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
  app/src/test/java/org/dhis2/bindings/RuleExtensionsTest.kt
Labels: Ready for merge, bug

#1238 fix: [ANDROAPP-2810] Can't enroll tei in program from dashboard list
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/teiProgramList/TeiProgramListRepositoryImplTest.kt
Labels: Ready for merge, Tested, bug

#1246 fix: [ANDROAPP-2790] TEType in coordinates label
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
Labels: Ready for merge, Tested, bug

#1247 fix: [ANDROAPP-2803] Updates Tei image on search list when it's updated.
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
Labels: Tested, bug

#1245 fix: [ANDROAPP-2813] Show full label in every field
  app/src/main/java/org/dhis2/Bindings/ValueTypeExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextCustomHolder.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentModule.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
  app/src/main/java/org/dhis2/utils/customviews/CustomTextView.java
  app/src/main/java/org/dhis2/utils/customviews/OptionSetView.java
  app/src/main/java/org/dhis2/utils/customviews/OrgUnitView.java
  app/src/main/res/layout/age_custom_view.xml
  app/src/main/res/layout/age_custom_view_accent.xml
  app/src/main/res/layout/custom_long_text_view.xml
  app/src/main/res/layout/custom_long_text_view_accent.xml
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/custom_text_view_accent.xml
  app/src/main/res/layout/date_time_view.xml
  app/src/main/res/layout/date_time_view_accent.xml
  app/src/main/res/layout/form_picture.xml
  app/src/main/res/layout/form_picture_accent.xml
  app/src/main/res/layout/form_spinner.xml
  app/src/main/res/layout/form_spinner_accent.xml
  app/src/main/res/layout/scan_text_view.xml
  app/src/main/res/layout/time_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
Labels: Ready for merge, Tested, bug

#1257 fix: [ANDROAPP-2818] Updates location of map when granting location permission.
  app/src/main/java/org/dhis2/usescases/map/MapSelectorActivity.kt
Labels: Ready for merge, Tested, bug

#1256 fix: [ANDROAPP-2820] Duplicated fields and crash in single section events
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/test/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterTest.kt
Labels: Ready for testing, bug

#1268 fix: [ANDROAPP-2818] Updates AbstractActivity to get the MapActivity's Constants
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
Labels: bug, waiting for approval

#1254 fix: [ANDROAPP-2817] Datasets yes/no value type rendering
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonHolder.java
  app/src/main/java/org/dhis2/data/forms/dataentry/tablefields/radiobutton/RadioButtonCellHolder.java
  app/src/main/java/org/dhis2/utils/customviews/YesNoView.java
  app/src/main/res/layout/yes_no_view_primary.xml
Labels: Ready for merge, bug

#1258 fix: [ANDROAPP-2819] check enrollment followUp is not null
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataFragment.java
Labels: Ready for merge, Tested, bug

#1265 style: [ANDROAPP-2822] Fix event form toolbar title style
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/res/layout/activity_event_capture.xml
Labels: Ready for merge, bug

#1266 style: [ANDROAPP-2821] Fix enrollment toolbar title
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/res/layout/tei_data_header.xml
Labels: Ready for testing, bug

#1269 style: [ANDROAPP-2824] Change color to section fields number when all fields have values
  app/src/main/java/org/dhis2/Bindings/ViewExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
Labels: Ready for merge, Tested, enhancement

#1267 fix: [ANDROAPP-2823] Fix add event when grouping events
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TEIDataPresenterImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/TeiDataRepositoryImpl.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/tei_events/EventViewModel.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/tei_events/StageViewHolder.kt
Labels: Ready for merge, Tested, bug

#1271 fix: [ANDROAPP-2814] Fix crash related to search list
  app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for testing, bug

#1272 fix: [ANDROAPP-2825] Add padding to parameter settings layout
  app/src/main/res/layout/fragment_settings.xml
Labels: bug, waiting for approval

#1273 test: [ANDROAPP-2568] DataSetTable Presenter Tests
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/test/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenterTest.kt
Labels: Ready for merge, Unit Test

#1278 fix: [ANDROAPP-2829] Changes colors of the percentage circle
  app/src/main/java/org/dhis2/utils/customviews/CircularCompletionView.java
  app/src/main/res/layout-land/activity_event_initial.xml
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/layout/activity_event_initial.xml
  app/src/main/res/values/colors.xml
Labels: Ready for merge, Tested, bug

#1277 fix: [ANDROAPP-2827] Fix inner shadow in last form field
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1276 fix: [ANDROAPP-2830] Fix grouping stage icon corner radius
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/tei_data/tei_events/StageViewHolder.kt
  app/src/main/res/drawable/square_rounded_corners_2.xml
Labels: Ready for merge, bug

#1280 fix: [ANDROAPP-2831] Sets elevation when filters are shown in the TEI Dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
Labels: Tested, bug

#1275 fix: [ANDROAPP-2783] Fix changing display text to display key value pair
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayHolder.java
Labels: Ready for merge, Tested, bug

#1282 fix: [ANDROAPP-2838] Do not delete values when hide section is activated
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
Labels: Ready for merge, Tested, bug

#1284 fix: [ANDROAPP-2839] treat displayViewModels as unsupported fields in…
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
Labels: Ready for merge, Tested, bug

#1283 fix: [ANDROAPP-2835] Display full image when clicked
  app/src/main/java/org/dhis2/Bindings/Extensions.kt
  app/src/main/java/org/dhis2/Bindings/FileExtensions.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureRow.java
  app/src/main/java/org/dhis2/utils/customviews/ImageDetailBottomDialog.kt
  app/src/main/java/org/dhis2/utils/customviews/PictureView.java
  app/src/main/res/layout/detail_image_bottom_dialog.xml
  app/src/main/res/layout/form_picture.xml
  app/src/test/java/org/dhis2/bindings/FileExtensionsTest.kt
Labels: Ready for merge, Tested, bug

#1281 fix: [ANDROAPP-2832] section error indicators
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionViewModel.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/res/drawable/bg_section_error.xml
  app/src/main/res/layout/form_section.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
Labels: Ready for merge, Tested, bug

#1287 fix: [ANDROAPP-2844] Change PreferenceProvider instead of SharedPreferences
  app/src/main/java/org/dhis2/data/service/SyncDataWorker.java
  app/src/main/java/org/dhis2/data/service/SyncMetadataWorker.java
Labels: Ready for merge, Tested, bug

#1289 fix: [ANDROAPP-2826] save values on clear
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
Labels: Ready for merge, Tested, bug

#1288 fix: [ANDROAPP-2828] Improve open/close section animation
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryAdapter.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/section/SectionHolder.kt
  app/src/main/res/drawable/shadow.xml
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/layout/enrollment_activity.xml
  app/src/main/res/layout/form_section.xml
  app/src/main/res/layout/section_selector_fragment.xml
Labels: Tested, bug

#1291 fix: [ANDROAPP-2846] TEI details title attributes
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
Labels: Ready for merge, Tested, bug

#1294 fix: [ANDROAPP-2847] Removes SharedPreferences from logout and uses instead the PreferenceProvider
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
Labels: Tested, bug

#1292 fix: [ANDROAPP-2807] Sets server url and user name of previous successful login.
  app/src/main/java/org/dhis2/usescases/login/LoginActivity.kt
  app/src/main/java/org/dhis2/usescases/login/LoginContracts.kt
  app/src/main/java/org/dhis2/usescases/login/LoginPresenter.kt
  app/src/test/java/org/dhis2/usescases/login/LoginPresenterTest.kt
Labels: Tested, bug

#1300 fix: [ANDROAPP-2852] Validates that a field of valueType of Number does not round decimals.
  app/src/main/java/org/dhis2/utils/ValidationUtils.kt
  app/src/test/java/org/dhis2/utils/ValidationUtilsTest.kt
Labels: Tested, bug

#1299 fix: [ANDROAPP-2856] change color and padding when there is a error
  app/src/main/java/org/dhis2/usescases/settings/SyncManagerFragment.java
  app/src/main/res/layout/fragment_settings_item.xml
Labels: Tested, bug

#1308 fix: [ANDROAPP-2864] ask only for fine location
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentActivity.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/map/MapSelectorActivity.kt
  app/src/main/java/org/dhis2/utils/customviews/CoordinatesView.java
Labels: Ready for merge, Tested, bug

#1307 fix: [ANDROAPP-2863] Fix crash in search screen
  app/src/main/java/org/dhis2/Bindings/TrackedEntityInstanceExtensions.kt
Labels: Ready for merge, Tested, bug

#1309 fix: [ANDROAPP-2866] Hide section rule should not delete field's values
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/main/java/org/dhis2/utils/UtilsModule.java
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.java
Labels: Tested, bug

#1296 fix: [ANDROAPP-2813]Fix labels for dataSets dataelement column
  app/src/main/java/org/dhis2/Bindings/MeasureExtensions.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableModule.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTablePresenter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetRowHeader.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetTableAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueModule.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/res/drawable/ic_increase_width.xml
  app/src/main/res/drawable/ic_reduce_width.xml
  app/src/main/res/layout/custom_cell_view.xml
  app/src/main/res/layout/item_dataset_row.xml
  app/src/main/res/layout/table_view_corner_layout.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/org/dhis2/usescases/datasets/DataValuePresenterTest.kt
  tableview/src/main/java/com/evrencoskun/tableview/ITableView.java
  tableview/src/main/java/com/evrencoskun/tableview/TableView.java
  tableview/src/main/java/com/evrencoskun/tableview/adapter/AbstractTableAdapter.java
Labels: Ready for merge, Tested, bug

#1310 fix: [ANDROAPP-2858] Prevents search when a minimum required attribute is needed
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_search_backup.xml
  app/src/test/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenterTest.kt
Labels: Tested, bug
