Repository dhis2/dhis2-android-capture-app, pull requests merged in 2021-02, with the labels that each got.

#1869 fix: [ANDROAPP-3598] Fix double focus in text fields
  app/src/main/java/org/dhis2/Bindings/Bindings.java
Labels: Ready for merge, Tested, bug

#1868 feat: [ANDROAPP-3494] Migrate Stetho to Flipper
  app/build.gradle
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/App.java
  app/src/main/java/org/dhis2/data/appinspector/AppInspector.kt
  app/src/main/java/org/dhis2/data/server/ServerModule.kt
Labels: enhancement

#1876 fix: [ANDROAPP-3629] Fix clear button for long text fields
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
Labels: Internal testing, bug

#1878 feat: [ANDROAPP-3562] Add item separator line to events
  app/src/main/res/layout/item_event.xml
Labels: Ready for merge, Tested, enhancement

#1875 feat: [ANDROAPP-3609] camera permissions in Image and Scan fields
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
  app/src/main/res/values/strings.xml
Labels: Internal testing, enhancement

#1880 feat: [ANDROAPP-3563] dataset cards design
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailModel.java
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailRepositoryImpl.java
  app/src/main/res/layout/item_dataset.xml
  app/src/test/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1885 feat: [ANDROAPP-3039] Enrolled org. unit is shown in tei cards
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/main/java/org/dhis2/Bindings/TEICardExtensions.kt
  app/src/main/java/org/dhis2/data/sorting/SearchSortingValueSetter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/BaseTeiViewHolder.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/RelationshipLiveAdapter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiLiveAdapter.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/data/sorting/SearchSortingValueSetterTest.kt
Labels: Ready for merge, Tested, enhancement

#1884 fix: [ANDROAPP-3643] Crash when selecting all programs in dashboard
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
  app/src/test/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepositoryTest.kt
Labels: Ready for merge, Tested, bug

#1886 fix: [ANDROAPP-3642] keyboard not closing after saving value
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
Labels: Ready for merge, Tested, bug

#1887 fix: [ANDROAPP-3652] set enable/disable for radioButton, checkButton and yesToggle via XML
  app/src/main/res/layout/form_check_button.xml
  app/src/main/res/layout/form_radio_button_horizontal.xml
  app/src/main/res/layout/form_toggle.xml
Labels: Ready for merge, Tested, bug

#1888 fix: [ANDROAPP-3645] Navigation bottom bar selected circle missbehaviour
  app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
Labels: Ready for merge, Tested, bug

#1890 fix: [ANDROAPP-3550] overlap TEI attribute label
  app/src/main/res/layout/item_carousel_tei.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: Ready for merge, Tested, bug

#1891 fix: [ANDROAPP-3578] Visual option set warning message
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/visualOptionSet/VisualOptionSetView.kt
Labels: Ready for merge, Tested, bug

#1895 feat: [ANDROAPP-1161] separate indicators by section
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueContract.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValuePresenter.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepository.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataValueRepositoryImpl.kt
Labels: Ready for merge, Tested, enhancement

#1901 fix: [Androapp-3664] PictureView Nullpointer Exception
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinateViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/datetime/DateTimeViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/display/DisplayViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/file/FileViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/orgUnit/OrgUnitViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/picture/PictureViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextViewModel.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/unsupported/UnsupportedViewModel.java
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for testing, bug

#1896 fix: [ANDROAPP-3584] Do not close activity when checking complete dataSet
  app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetIntents.kt
  app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTableRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/datasets/DataSetTest.kt
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1897 fix: [ANDROAPP-3547] Incorrect Category Option selection
  app/src/main/java/org/dhis2/utils/customviews/CatOptionPopUp.kt
Labels: Ready for merge, Tested, bug

#1898 feat: [ANDROAPP-3655] Block swipe in tei dashboard
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
Labels: Ready for merge, Tested, enhancement

#1892 fix: [ANDROAPP-651] Working list should not be visible in dashboard
  app/src/main/java/org/dhis2/data/filter/FilterRepository.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
  app/src/main/java/org/dhis2/utils/filters/FilterItem.kt
  app/src/main/java/org/dhis2/utils/filters/FilterManager.java
  app/src/main/java/org/dhis2/utils/filters/workingLists/WorkingListChipGroup.kt
  app/src/main/java/org/dhis2/utils/filters/workingLists/WorkingListItem.kt
  app/src/main/res/layout/item_filter_working_list.xml
Labels: Ready for merge, Tested, bug

#1905 fix: [ANDROAPP-3679] Shows orgUnit when TEI is online
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1906 fix: [ANDROAPP-1161] set max width to indicator label
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/dataSetSection/DataSetSectionFragment.kt
  tableview/src/main/res/layout/item_table_header.xml
Labels: Ready for merge, Tested, bug

#1909 fix: [ANDROAPP-3585] Fix Date test
  app/src/main/java/org/dhis2/Bindings/DateExtensions.kt
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/test/java/org/dhis2/bindings/DateExtensionsTest.kt
  app/src/test/java/org/dhis2/utils/DateUtilsTest.java
Labels: Ready for merge, bug

#1900 fix: [ANDROAPP-3665] filter null attributes in enrollment form
  app/src/main/java/org/dhis2/data/dhislogic/DhisEnrollmentUtils.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
Labels: Ready for merge, Tested, bug

#1910 feat: [ANDROAPP-3579] hide ans show bottom nav in events form
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureContract.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePresenterImpl.java
  app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
Labels: Internal testing, enhancement

#1899 feat: [ANDROAPP-3633] Break the glass dialog
  app/src/main/java/org/dhis2/usescases/development/DevelopmentActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/java/org/dhis2/utils/customviews/BreakTheGlassBottomDialog.kt
  app/src/main/res/color/break_glass_color_selector.xml
  app/src/main/res/layout/break_the_glass_bottom_dialog.xml
  app/src/main/res/layout/development_activity.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: Ready for merge, Tested, enhancement

#1907 fix: [ANDROAPP-3467] Navigation button visibility
  app/src/main/java/org/dhis2/animations/CarouselViewAnimations.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/adapters/SearchTeiModel.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
Labels: Internal testing, bug

#1903 feat: [ANDROAPP-3663] implement reset filters design
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/java/org/dhis2/usescases/main/program/ProgramFragment.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/res/drawable/ic_map_layers.xml
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout-land/fragment_program.xml
  app/src/main/res/layout/activity_dataset_detail.xml
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_program.xml
  app/src/main/res/layout/item_dataset.xml
Labels: Ready for merge, Tested, enhancement

#1893 fix: [ANDROAPP-3563] capitalize dataset period
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/test/java/org/dhis2/utils/DateUtilsTest.java
Labels: Internal testing, bug

#1911 fix: [ANDROAPP-3582] Validations error view reacts to keyboard visibility.
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
Labels: Ready for merge, Tested, bug

#1918 feat: [ANDROAPP-2578] display error/warning message on whole field
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/age/AgeView.java
  app/src/main/res/layout/age_custom_view.xml
  app/src/main/res/layout/age_custom_view_accent.xml
Labels: Ready for merge, Tested, enhancement

#1913 feat: [ANDROAPP-3312] Data element legends
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRepository.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactory.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/LegendValue.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/CustomTextView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/OptionSetView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/spinner/SpinnerViewModel.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventSummary/EventSummaryRepositoryImpl.java
  app/src/main/res/drawable/data_element_legend_background.xml
  app/src/main/res/drawable/data_element_legend_badge.xml
  app/src/main/res/layout/custom_text_view.xml
  app/src/main/res/layout/data_element_legend.xml
  app/src/main/res/layout/form_spinner.xml
  app/src/test/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImplTest.kt
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
  app/src/test/java/org/dhis2/utils/customviews/FormBottomDialogPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1919 fix: [ANDROAPP-3562] Event card height to fix item divider on tei dashboard.
  app/src/main/res/layout/item_event.xml
Labels: Ready for merge, Tested, bug

#1922 fix: [ANDROAPP-3648] Map layers button showing on list view mode
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
Labels: Ready for merge, Tested, bug

#1924 fix: [ANDROAPP-3717] Review navigation to details section
  app/src/androidTest/java/org/dhis2/usescases/event/EventRegistrationRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/event/EventTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/EventRobot.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/utils/customviews/DhisBottomNavigationBar.kt
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/menu/event_menu.xml
  app/src/main/res/menu/navigation_event_menu.xml
  app/src/main/res/values/attrs.xml
Labels: Ready for merge, Tested, bug

#1921 fix: [ANDROAPP-3688] crash on show help
  app/src/main/java/org/dhis2/utils/HelpManager.java
Labels: Ready for merge, Tested, bug

#1925 fix: [ANDROAPP-3675] keyboard displayed on home
  app/src/main/res/layout/filter_org_unit.xml
Labels: Ready for merge, Tested, bug

#1920 fix: [ANDROAPP-3677] Fix crash on MapSelectorActivity initialization
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/coordinate/CoordinatesView.java
  app/src/main/java/org/dhis2/uicomponents/map/extensions/MapExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/polygon/PolygonViewModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/MapSelectorActivity.kt
  app/src/main/java/org/dhis2/usescases/enrollment/EnrollmentPresenterImpl.kt
Labels: Ready for merge, Tested, bug

#1923 fix: [ANDROAPP-3661] Text overlap in tei search activity
  app/src/main/res/layout/item_search_tracked_entity.xml
Labels: Ready for merge, Tested, bug

#1926 fix: [ANDROAPP-3690] Separates carousel initialization from activity
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Ready for merge, Tested, bug

#1928 fix: [ANDROAPP-3723] crash scrolling carousel
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
Labels: Ready for merge, Tested, bug
