Repository dhis2/dhis2-android-capture-app, pull requests merged in 2021-01, with the labels that each got.

#1827 feat: [ANDROAPP-3540] Adds Bar ChartType to the analytics module
  app/src/androidTest/java/org/dhis2/common/matchers/ChartMatchers.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/data/analytics/AnalyticsModel.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/ChartViewHolder.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsView.kt
  app/src/main/res/menu/dashboard_menu.xml
  app/src/main/res/menu/dashboard_menu_group.xml
  app/src/main/res/values/strings.xml
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphCoordinatesToBarEntry.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarData.kt
Labels: Ready for merge, Tested, enhancement

#1839 feat: [Androapp-3517] Implement new navigation in event forms
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/res/layout/activity_event_capture.xml
  app/src/main/res/layout/fragment_notes.xml
  app/src/main/res/menu/navigation_event_menu.xml
Labels: Internal testing, enhancement

#1838 feat: [ANDROAPP-3518] New navigation in data sets
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetSectionAdapter.java
  app/src/main/java/org/dhis2/usescases/datasets/dataSetTable/DataSetTableActivity.java
  app/src/main/res/layout/activity_dataset_table.xml
  app/src/main/res/layout/fragment_dataset_section.xml
  app/src/main/res/menu/navigation_dataset_menu.xml
Labels: Internal testing, enhancement

#1834 feat: [ANDROAPP-3515] add BottomNavigation to search
  app/src/androidTest/java/org/dhis2/usescases/searchte/SearchTETest.kt
  app/src/androidTest/java/org/dhis2/usescases/searchte/robot/SearchTeiRobot.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/res/drawable/ic_search_add.xml
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_search_tracked_entity.xml
  app/src/main/res/menu/search_menu.xml
Labels: Internal testing, enhancement

#1845 fix: [ANDROAPP-3588] Show/hide Fab button when bottom is reached
  app/src/main/java/org/dhis2/data/forms/dataentry/FormView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormFragment.java
Labels: Ready for merge, Tested, bug

#1847 fix: [ANDROAPP-3592] Cat. Option combo selector not showing up
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialPresenter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventInitial/EventInitialRepositoryImpl.java
Labels: Ready for merge, Tested, bug

#1848 feat: [ANDROAPP-3542] render analytic data as table
  app/src/androidTest/java/org/dhis2/common/matchers/ChartMatchers.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/res/layout/item_chart.xml
  app/src/main/res/menu/dashboard_menu.xml
  app/src/main/res/menu/dashboard_menu_group.xml
  app/src/main/res/values/strings.xml
  dhis_android_analytics/build.gradle
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Chart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/ChartType.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/di/ChartsInjector.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToBarChart.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/mappers/GraphToTable.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableAdapter.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/table/GraphTableHolder.kt
  dhis_android_analytics/src/main/res/layout/item_table_cell.xml
  dhis_android_analytics/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, enhancement

#1841 fix: [ANDROAPP-3555] Radiobutton misbehaviour
  app/src/main/java/org/dhis2/Bindings/Bindings.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/radiobutton/RadioButtonViewModel.java
  app/src/main/res/layout/form_radio_button_horizontal.xml
Labels: Ready for merge, Tested, bug

#1853 fix: [ANDROAPP-3600] Add click listener when showing info dialog on log in
  app/src/main/java/org/dhis2/usescases/general/ActivityGlobalAbstract.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
Labels: bug, waiting for approval

#1852 fix: [ANDROAPP-3574] check overdue events
  app/src/main/java/org/dhis2/data/dhislogic/DhisTrackedEntityInstanceUtils.kt
Labels: Ready for merge, Tested, bug

#1850 fix: [ANDROAPP-3471] Sticky section header now sticks
  app/src/main/java/org/dhis2/data/forms/dataentry/DataEntryHeaderHelper.kt
  app/src/main/java/org/dhis2/data/forms/dataentry/SectionHandler.kt
Labels: bug

#1849 fix: Scanview multiple binding
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
Labels: Ready for testing, bug

#1851 fix: [ANDROAPP-3515] display message over map and hide fabutton on map
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEContractsModule.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEPresenter.java
  app/src/main/res/layout/activity_search.xml
Labels: Ready for merge, Tested, bug

#1856 feat: [ANDROAPP-3544] Add feedback and indicator widgets for ruleActions
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/TeiDashboardTest.kt
  app/src/androidTest/java/org/dhis2/usescases/teidashboard/robot/IndicatorsRobot.kt
  app/src/main/assets/paperwork.json
  app/src/main/java/org/dhis2/Bindings/RuleExtensions.kt
  app/src/main/java/org/dhis2/data/analytics/AnalyticsModel.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardMobileActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsModule.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/main/res/drawable/ic_compass.xml
  app/src/main/res/drawable/ic_layers.xml
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/item_section_tittle.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterTest.kt
Labels: Ready for merge, Tested, enhancement

#1811 feat: [ANDROAPP-3467] Opens default map app to the TEI's location
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselTeiHolder.kt
  app/src/main/java/org/dhis2/uicomponents/map/geometry/FeatureExtensions.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/managers/TeiMapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/relationships/RelationshipFragment.java
  app/src/main/res/drawable/ic_map_navigate.xml
  app/src/main/res/layout/item_carousel_tei.xml
Labels: Ready for testing, enhancement

#1857 fix: [ANDROAPP-3601] display attributes when open card on program events
  app/src/main/java/org/dhis2/animations/ViewAnimations.kt
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselProgramEventHolder.kt
Labels: Ready for merge, Tested, bug

#1807 docs: update webapp images and manual option [skip ci]
  docs/src/commonmark/en/content/capture-app/app-android-settings-configuration.md
  docs/src/commonmark/en/content/capture-app/resources/images/dataset-global-settings.png
  docs/src/commonmark/en/content/capture-app/resources/images/dataset-specific-dialog.png
  docs/src/commonmark/en/content/capture-app/resources/images/dataset-specific-table.png
  docs/src/commonmark/en/content/capture-app/resources/images/general-settings.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-global-settings.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-specific-dialog-with_registration.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-specific-dialog-without_registration.png
  docs/src/commonmark/en/content/capture-app/resources/images/program-specific-table.png
Labels: Documentation

#1862 fix: update target version
  app/src/androidTest/java/org/dhis2/common/BaseRobot.kt
  buildsystem/dependencies.gradle
Labels: bug, waiting for approval

#1863 feat: Kujaku library
  app/build.gradle
  build.gradle
  buildsystem/dependencies.gradle
Labels: enhancement, waiting for approval

#1858 feat: [ANDROAPP-3463] Display indicators in Events from event programs
  app/src/main/java/org/dhis2/data/forms/dataentry/EnrollmentRuleEngineRepository.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureActivity.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureComponent.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureModule.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCapturePagerAdapter.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventCaptureRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/EventRuleEngineRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/TeiDashboardModule.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/adapters/DashboardPagerAdapter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/BaseIndicatorRepository.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/EventIndicatorRepository.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorInjector.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorRepository.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsFragment.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsModule.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/TrackerAnalyticsRepository.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/VisualizationType.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataModule.java
  app/src/main/java/org/dhis2/utils/RulesUtilsProvider.kt
  app/src/main/java/org/dhis2/utils/RulesUtilsProviderImpl.kt
  app/src/main/java/org/dhis2/utils/resources/ResourceManager.kt
  app/src/main/res/menu/navigation_event_menu.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/EventIndicatorRepositoryTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/IndicatorsPresenterTest.kt
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/indicators/TrackerAnalyticsRepositoryTest.kt
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/ChartsRepositoryImpl.kt
  dhis_android_analytics/src/main/java/dhis2/org/analytics/charts/data/Graph.kt
Labels: Ready for merge, Tested, enhancement

#1865 fix: [ANDROAPP-3515] change clear filter icon and add it to map
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/drawable/bg_image_marker.xml
  app/src/main/res/drawable/ic_refresh.xml
  app/src/main/res/layout-land/activity_search.xml
  app/src/main/res/layout-land/fragment_program.xml
  app/src/main/res/layout/activity_dataset_detail.xml
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/fragment_program.xml
Labels: Ready for merge, Tested, bug

#1864 fix: [ANDROAPP-3623] Correctly handles camera permission when not granted.
  app/src/main/java/org/dhis2/usescases/main/MainActivity.kt
  app/src/main/java/org/dhis2/usescases/qrReader/QrReaderFragment.java
  app/src/main/java/org/dhis2/usescases/qrScanner/ScanActivity.kt
  app/src/main/java/org/dhis2/utils/customviews/ScanTextView.kt
  app/src/main/res/values/strings.xml
Labels: Ready for merge, Tested, bug

#1867 feat: [ANDROAPP-3377] Add test sharding 2 paralell devices
  scripts/browserstackBitrise.sh
  scripts/config.init
Labels: Ready for testing, enhancement
