Repository dhis2/dhis2-android-capture-app, pull requests merged in 2021-03, with the labels that each got.

#1930 fix: [ANDROAPP-3701] Clear assign to me filter when going back to home screen
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
Labels: Internal testing, bug

#1931 fix: [ANDROAPP-3718] Add navigation bar to ProgramEventDetailActivity
  app/src/main/java/org/dhis2/uicomponents/map/carousel/CarouselAdapter.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailActivity.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailComponent.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailContract.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailLiveAdapter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailModule.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenter.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepository.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailViewModel.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragment.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListFragmentView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListInjector.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventList/EventListPresenter.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragment.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapFragmentView.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapInjector.kt
  app/src/main/java/org/dhis2/usescases/programEventDetail/eventMap/EventMapPresenter.kt
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/res/layout/activity_program_event_detail.xml
  app/src/main/res/layout/fragment_program_event_detail_list.xml
  app/src/main/res/layout/fragment_program_event_detail_map.xml
  app/src/main/res/menu/event_list_menu.xml
  app/src/main/res/menu/navigation_event_list.xml
  app/src/test/java/org/dhis2/usescases/programEventDetail/ProgramEventDetailPresenterTest.kt
Labels: Internal testing, bug

#1940 fix: [ANDROAPP-3741] Fix Crash with enrollment date when going to home screen
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/main/java/org/dhis2/utils/filters/dates/FilterPeriodView.kt
Labels: Internal testing, bug

#1933 fix: [ANDROAPP-3715] Filtering Dates
  app/src/main/java/org/dhis2/utils/DateUtils.java
  app/src/test/java/org/dhis2/utils/DateUtilsTest.java
Labels: bug, changes requested

#1927 feat: [ANDROAPP-3441] Update testing database
  app/src/androidTest/java/org/dhis2/common/db/TestingDatabase.kt
  scripts/updateTestingDB.py
Labels: Ready for merge, Tested, enhancement

#1937 fix: [ANDROAPP-3580] set options for option set selection and change …
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/FieldViewModelFactoryImpl.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetSelectionView.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/optionset/OptionSetViewModel.java
  app/src/main/res/layout/form_spinner_selection.xml
  app/src/main/res/layout/form_spinner_selection_accent.xml
  app/src/main/res/layout/option_set_select_check_item.xml
  app/src/main/res/layout/option_set_select_item.xml
Labels: Internal testing, bug

#1934 fix: [ANDROAPP-3705] dataset orgunit visibility
  app/src/main/java/org/dhis2/usescases/datasets/datasetDetail/DataSetDetailActivity.java
  app/src/main/res/layout/item_dataset.xml
Labels: Ready for merge, Tested, bug

#1932 fix: [Androapp-3653] Analytics table width changes
  tableview/src/main/res/layout/item_table_cell.xml
  tableview/src/main/res/layout/item_table_header.xml
Labels: Internal testing, bug

#1942 fix: [ANDROAPP-3746] share event values through QR
  app/src/main/java/org/dhis2/usescases/qrReader/QrReaderPresenterImpl.java
Labels: Internal testing, bug

#1946 fix: [ANDROAPP-3747] When image is clicked fields become editable
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/edittext/EditTextViewModel.java
  app/src/main/java/org/dhis2/data/forms/dataentry/fields/scan/ScanTextView.kt
  app/src/main/java/org/dhis2/usescases/eventsWithoutRegistration/eventCapture/eventCaptureFragment/EventCaptureFormPresenter.kt
  app/src/test/java/org/dhis2/utils/RulesUtilsProviderImplTest.kt
Labels: Internal testing, bug

#1945 fix: [ANDROAPP-3711] Allow re select selected item in Spinner
  app/src/main/java/org/dhis2/Bindings/Bindings.java
Labels: Ready for merge, Tested, bug

#1939 fix: [ANDROAPP-3663] don't hide filterOpen layout
  app/src/main/java/org/dhis2/usescases/searchTrackEntity/SearchTEActivity.java
  app/src/main/res/layout/activity_search.xml
Labels: Internal testing, bug

#1935 fix: [ANDROAPP-3703] Avoid CarouselView crash
  app/src/main/java/org/dhis2/uicomponents/map/managers/MapManager.kt
  app/src/main/java/org/dhis2/uicomponents/map/views/CarouselView.kt
Labels: Ready for merge, Tested, bug

#1941 fix: [ANDROAPP-3742] Add access control to dashboard catCombo dialog
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepository.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/DashboardRepositoryImpl.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataContracts.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataFragment.java
  app/src/main/java/org/dhis2/usescases/teiDashboard/dashboardfragments/teidata/TEIDataPresenterImpl.java
  app/src/test/java/org/dhis2/usescases/teiDashboard/dashboardfragments/data/TeiDataPresenterImplTest.kt
Labels: Internal testing, bug

#1944 fix: [ANDROAPP-3749] Fixed unique value warning
  app/src/main/java/org/dhis2/data/forms/dataentry/ValueStoreImpl.kt
  app/src/test/java/org/dhis2/data/forms/dataentry/ValueStoreTest.kt
Labels: Ready for merge, Tested, bug

#1936 fix: [ANDROAPP-3716] Avoid hiding last edit text with keyboard
  app/src/debug/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
Labels: Internal testing, bug

#1949 fix: [ANDROAPP-3727] padding in tableview
  app/src/main/res/layout/fragment_dataset_section.xml
Labels: Ready for merge, Tested, bug
